root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  pre_cmd = []
  cmd = "go build -o ./tmp/api ./cmd/api"
  bin = "./tmp/api"
  full_bin = ""
  args_bin = []
  include_ext = ["go", "sql", "tmpl", "tpl", "html"]
  exclude_dir = ["tmp", "bin", "testdata", "vendor", "sqlc/queries"]
  include_dir = []
  include_file = []
  exclude_file = []
  exclude_regex = ["_test\\.go"]
  exclude_unchanged = true
  follow_symlink = false
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  delay = 800
  stop_on_error = true
  send_interrupt = true
  kill_delay = "2s"
  rerun = false
  rerun_delay = 500
  post_cmd = []

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = false
  keep_scroll = true
