/**
 * Cross-engine parity check.
 *
 * The Go split engine (`backend/internal/split`) is the source of truth for
 * how an expense gets divided. This test reads a fixture file generated by
 * `TestSplit_FixtureExport` in that package and asserts the TypeScript port
 * in `app/lib/split.ts` produces byte-identical output.
 *
 * **Regenerate the fixture before running this test:**
 *
 *   cd backend && go test ./internal/split -run TestSplit_FixtureExport
 *
 * The file lives at `backend/testdata/split-fixture.json` and is checked
 * into source control. If it's missing this test will fail with a clear
 * message instructing how to regenerate it.
 */

import * as fs from 'fs';
import * as path from 'path';
import { computeSplits } from '../split';

type FixtureExpected = { memberId: string; amountMinor: number };

type FixtureCase = {
  name: string;
  method: 'equal' | 'exact' | 'percentage';
  amountMinor: number;
  participants?: string[];
  exactShares?: { memberId: string; amountMinor: number }[];
  percentageShares?: { memberId: string; basisPoints: number }[];
  expected: FixtureExpected[];
};

const FIXTURE_PATH = path.resolve(
  __dirname,
  '..',
  '..',
  '..',
  'backend',
  'testdata',
  'split-fixture.json',
);

function loadFixture(): FixtureCase[] {
  if (!fs.existsSync(FIXTURE_PATH)) {
    throw new Error(
      `split-fixture.json not found at ${FIXTURE_PATH}.\n` +
        `Regenerate it with: cd backend && go test ./internal/split -run TestSplit_FixtureExport`,
    );
  }
  return JSON.parse(fs.readFileSync(FIXTURE_PATH, 'utf8')) as FixtureCase[];
}

describe('split engine — cross-language parity with Go', () => {
  const cases = loadFixture();

  it('fixture has at least 10 cases covering all three methods', () => {
    expect(cases.length).toBeGreaterThanOrEqual(10);
    const methods = new Set(cases.map((c) => c.method));
    expect(methods.has('equal')).toBe(true);
    expect(methods.has('exact')).toBe(true);
    expect(methods.has('percentage')).toBe(true);
  });

  for (const tc of cases) {
    it(`matches Go for ${tc.method}: ${tc.name}`, () => {
      const amount = BigInt(tc.amountMinor);
      let actual;
      switch (tc.method) {
        case 'equal':
          actual = computeSplits(amount, 'equal', tc.participants!);
          break;
        case 'exact': {
          const inputs = (tc.exactShares ?? []).map((s) => ({
            memberId: s.memberId,
            amountMinor: BigInt(s.amountMinor),
          }));
          const participants = inputs.map((s) => s.memberId);
          actual = computeSplits(amount, 'exact', participants, inputs);
          break;
        }
        case 'percentage': {
          // The fixture stores basis points (Go-native). We translate to the
          // TS API by dividing by 100 → percentage. This guarantees no
          // round-trip drift because we go back through `Math.round(p * 100)`
          // inside `computeSplits`.
          const inputs = (tc.percentageShares ?? []).map((s) => ({
            memberId: s.memberId,
            percentage: s.basisPoints / 100,
          }));
          const participants = inputs.map((s) => s.memberId);
          actual = computeSplits(amount, 'percentage', participants, inputs);
          break;
        }
      }

      // Compare element-by-element so the failure message is readable.
      const expected = tc.expected.map((e) => ({
        memberId: e.memberId,
        amountMinor: BigInt(e.amountMinor),
      }));
      expect(actual).toHaveLength(expected.length);
      for (let i = 0; i < expected.length; i++) {
        expect({
          memberId: actual![i].memberId,
          amountMinor: actual![i].amountMinor.toString(),
        }).toEqual({
          memberId: expected[i].memberId,
          amountMinor: expected[i].amountMinor.toString(),
        });
      }
    });
  }
});
