// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ai_generations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAIGenerationsBefore = `-- name: DeleteAIGenerationsBefore :exec
DELETE FROM ai_generations WHERE created_at < $1
`

func (q *Queries) DeleteAIGenerationsBefore(ctx context.Context, createdAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteAIGenerationsBefore, createdAt)
	return err
}

const insertAIGeneration = `-- name: InsertAIGeneration :exec
INSERT INTO ai_generations (
    id, user_id, feature, group_id, model,
    input_tokens, output_tokens, clip_ms, request_bytes, latency_ms,
    outcome, error_class,
    expense_count, question_count, degraded_split_count, unresolved_member_count
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12,
    $13, $14, $15, $16
)
`

type InsertAIGenerationParams struct {
	ID                    string      `db:"id" json:"id"`
	UserID                string      `db:"user_id" json:"user_id"`
	Feature               string      `db:"feature" json:"feature"`
	GroupID               pgtype.Text `db:"group_id" json:"group_id"`
	Model                 string      `db:"model" json:"model"`
	InputTokens           pgtype.Int4 `db:"input_tokens" json:"input_tokens"`
	OutputTokens          pgtype.Int4 `db:"output_tokens" json:"output_tokens"`
	ClipMs                pgtype.Int4 `db:"clip_ms" json:"clip_ms"`
	RequestBytes          pgtype.Int4 `db:"request_bytes" json:"request_bytes"`
	LatencyMs             int32       `db:"latency_ms" json:"latency_ms"`
	Outcome               string      `db:"outcome" json:"outcome"`
	ErrorClass            pgtype.Text `db:"error_class" json:"error_class"`
	ExpenseCount          int32       `db:"expense_count" json:"expense_count"`
	QuestionCount         int32       `db:"question_count" json:"question_count"`
	DegradedSplitCount    int32       `db:"degraded_split_count" json:"degraded_split_count"`
	UnresolvedMemberCount int32       `db:"unresolved_member_count" json:"unresolved_member_count"`
}

func (q *Queries) InsertAIGeneration(ctx context.Context, arg InsertAIGenerationParams) error {
	_, err := q.db.Exec(ctx, insertAIGeneration,
		arg.ID,
		arg.UserID,
		arg.Feature,
		arg.GroupID,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.ClipMs,
		arg.RequestBytes,
		arg.LatencyMs,
		arg.Outcome,
		arg.ErrorClass,
		arg.ExpenseCount,
		arg.QuestionCount,
		arg.DegradedSplitCount,
		arg.UnresolvedMemberCount,
	)
	return err
}

const linkAIGenerationExpense = `-- name: LinkAIGenerationExpense :exec
INSERT INTO ai_generation_expenses (generation_id, expense_id, changed_fields)
VALUES ($1, $2, $3)
ON CONFLICT (generation_id, expense_id) DO NOTHING
`

type LinkAIGenerationExpenseParams struct {
	GenerationID  string   `db:"generation_id" json:"generation_id"`
	ExpenseID     string   `db:"expense_id" json:"expense_id"`
	ChangedFields []string `db:"changed_fields" json:"changed_fields"`
}

// Best-effort link from a saved expense back to the generation that
// proposed it. ON CONFLICT DO NOTHING because a retry must not error.
func (q *Queries) LinkAIGenerationExpense(ctx context.Context, arg LinkAIGenerationExpenseParams) error {
	_, err := q.db.Exec(ctx, linkAIGenerationExpense, arg.GenerationID, arg.ExpenseID, arg.ChangedFields)
	return err
}
