// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: balances.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMemberBalance = `-- name: GetMemberBalance :one
SELECT group_id, member_id, user_id, currency, net_balance FROM member_balances
WHERE group_id = $1 AND member_id = $2
`

type GetMemberBalanceParams struct {
	GroupID  string `db:"group_id" json:"group_id"`
	MemberID string `db:"member_id" json:"member_id"`
}

func (q *Queries) GetMemberBalance(ctx context.Context, arg GetMemberBalanceParams) (MemberBalance, error) {
	row := q.db.QueryRow(ctx, getMemberBalance, arg.GroupID, arg.MemberID)
	var i MemberBalance
	err := row.Scan(
		&i.GroupID,
		&i.MemberID,
		&i.UserID,
		&i.Currency,
		&i.NetBalance,
	)
	return i, err
}

const listGroupBalances = `-- name: ListGroupBalances :many
SELECT group_id, member_id, user_id, currency, net_balance FROM member_balances
WHERE group_id = $1 AND currency IS NOT NULL
`

func (q *Queries) ListGroupBalances(ctx context.Context, groupID string) ([]MemberBalance, error) {
	rows, err := q.db.Query(ctx, listGroupBalances, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemberBalance{}
	for rows.Next() {
		var i MemberBalance
		if err := rows.Scan(
			&i.GroupID,
			&i.MemberID,
			&i.UserID,
			&i.Currency,
			&i.NetBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserBalancesAcrossGroups = `-- name: ListUserBalancesAcrossGroups :many
SELECT mb.group_id, mb.member_id, mb.user_id, mb.currency, mb.net_balance FROM member_balances mb
WHERE mb.user_id = $1 AND mb.currency IS NOT NULL
`

func (q *Queries) ListUserBalancesAcrossGroups(ctx context.Context, userID pgtype.Text) ([]MemberBalance, error) {
	rows, err := q.db.Query(ctx, listUserBalancesAcrossGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemberBalance{}
	for rows.Next() {
		var i MemberBalance
		if err := rows.Scan(
			&i.GroupID,
			&i.MemberID,
			&i.UserID,
			&i.Currency,
			&i.NetBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
