// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: balances.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMemberBalance = `-- name: GetMemberBalance :one
SELECT group_id, member_id, user_id, currency, net_balance FROM member_balances
WHERE group_id = $1 AND member_id = $2
`

type GetMemberBalanceParams struct {
	GroupID  string `db:"group_id" json:"group_id"`
	MemberID string `db:"member_id" json:"member_id"`
}

func (q *Queries) GetMemberBalance(ctx context.Context, arg GetMemberBalanceParams) (MemberBalance, error) {
	row := q.db.QueryRow(ctx, getMemberBalance, arg.GroupID, arg.MemberID)
	var i MemberBalance
	err := row.Scan(
		&i.GroupID,
		&i.MemberID,
		&i.UserID,
		&i.Currency,
		&i.NetBalance,
	)
	return i, err
}

const listGroupBalances = `-- name: ListGroupBalances :many
SELECT group_id, member_id, user_id, currency, net_balance FROM member_balances
WHERE group_id = $1 AND currency IS NOT NULL
`

func (q *Queries) ListGroupBalances(ctx context.Context, groupID string) ([]MemberBalance, error) {
	rows, err := q.db.Query(ctx, listGroupBalances, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemberBalance{}
	for rows.Next() {
		var i MemberBalance
		if err := rows.Scan(
			&i.GroupID,
			&i.MemberID,
			&i.UserID,
			&i.Currency,
			&i.NetBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserBalancesAcrossGroups = `-- name: ListUserBalancesAcrossGroups :many
SELECT mb.group_id, mb.member_id, mb.user_id, mb.currency, mb.net_balance FROM member_balances mb
WHERE mb.user_id = $1 AND mb.currency IS NOT NULL
`

func (q *Queries) ListUserBalancesAcrossGroups(ctx context.Context, userID pgtype.Text) ([]MemberBalance, error) {
	rows, err := q.db.Query(ctx, listUserBalancesAcrossGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemberBalance{}
	for rows.Next() {
		var i MemberBalance
		if err := rows.Scan(
			&i.GroupID,
			&i.MemberID,
			&i.UserID,
			&i.Currency,
			&i.NetBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserLedgerLegs = `-- name: ListUserLedgerLegs :many
SELECT
    'expense'                                    AS source,
    e.id                                         AS leg_id,
    e.group_id                                   AS group_id,
    COALESCE(e.expense_date, e.created_at::date) AS occurred_at,
    (CASE WHEN e.paid_by_id = gm.id THEN e.amount ELSE 0 END
        - COALESCE(es.share, 0))::BIGINT         AS signed_minor,
    e.currency                                   AS currency
FROM group_members gm
JOIN expenses e
    ON e.group_id = gm.group_id
    AND NOT e.is_deleted
    AND NOT e.is_reimbursement
LEFT JOIN expense_splits es
    ON es.expense_id = e.id AND es.member_id = gm.id
WHERE gm.user_id = $1
  AND gm.removed_at IS NULL
  AND (e.paid_by_id = gm.id OR es.share IS NOT NULL)

UNION ALL

SELECT
    'settlement'                  AS source,
    s.id                          AS leg_id,
    s.group_id                    AS group_id,
    s.created_at::date            AS occurred_at,
    (CASE WHEN s.from_member = gm.id THEN s.amount
          ELSE -s.amount END)::BIGINT AS signed_minor,
    s.currency                    AS currency
FROM group_members gm
JOIN settlements s
    ON s.group_id = gm.group_id
    AND s.reverted_at IS NULL
    AND (s.from_member = gm.id OR s.to_member = gm.id)
WHERE gm.user_id = $1 AND gm.removed_at IS NULL
`

type ListUserLedgerLegsRow struct {
	Source      string      `db:"source" json:"source"`
	LegID       string      `db:"leg_id" json:"leg_id"`
	GroupID     string      `db:"group_id" json:"group_id"`
	OccurredAt  pgtype.Date `db:"occurred_at" json:"occurred_at"`
	SignedMinor int64       `db:"signed_minor" json:"signed_minor"`
	Currency    string      `db:"currency" json:"currency"`
}

// Per-leg ledger entries that contribute to a user's net across every group
// they're a member of. Each row is denominated in the row's canonical
// (group) currency — the per-expense fx_rate was already applied
// server-side at write time, so `signed_minor` is the final number for
// balance math. The home-currency aggregator converts each leg to home
// using ECB rates at the leg's `occurred_at` date (never today's rate).
//
// Expense legs: (amount paid by user, if any) − (user's share). Reimbursements
// skipped (they're balance-neutral by definition). Reverted settlements
// skipped. Same convention as `member_balances`.
//
// Settlement legs: +amount when user is from_member (debt cleared, more
// owed-to-them); −amount when user is to_member.
func (q *Queries) ListUserLedgerLegs(ctx context.Context, userID pgtype.Text) ([]ListUserLedgerLegsRow, error) {
	rows, err := q.db.Query(ctx, listUserLedgerLegs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserLedgerLegsRow{}
	for rows.Next() {
		var i ListUserLedgerLegsRow
		if err := rows.Scan(
			&i.Source,
			&i.LegID,
			&i.GroupID,
			&i.OccurredAt,
			&i.SignedMinor,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
