// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: expenses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveExpensesByGroup = `-- name: CountActiveExpensesByGroup :one
SELECT COUNT(*) FROM expenses WHERE group_id = $1 AND NOT is_deleted
`

// Active = not soft-deleted. Used to lock the group currency once any real
// expense exists, since the member_balances view groups by expenses.currency
// and changing it mid-flight would fragment balances into per-currency
// buckets.
func (q *Queries) CountActiveExpensesByGroup(ctx context.Context, groupID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveExpensesByGroup, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpense = `-- name: CreateExpense :one

INSERT INTO expenses (
    id, group_id, title, amount, currency, paid_by_id, split_method, category, notes,
    expense_date, is_reimbursement, created_by_id,
    original_amount, original_currency, fx_rate, fx_as_of, fx_source
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
RETURNING id, group_id, title, amount, currency, paid_by_id, split_method, category, notes,
          expense_date, is_reimbursement, is_deleted, created_by_id, created_at, updated_at,
          original_amount, original_currency, fx_rate, fx_as_of, fx_source
`

type CreateExpenseParams struct {
	ID               string         `db:"id" json:"id"`
	GroupID          string         `db:"group_id" json:"group_id"`
	Title            string         `db:"title" json:"title"`
	Amount           int64          `db:"amount" json:"amount"`
	Currency         string         `db:"currency" json:"currency"`
	PaidByID         string         `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod      string         `db:"split_method" json:"split_method"`
	Category         string         `db:"category" json:"category"`
	Notes            pgtype.Text    `db:"notes" json:"notes"`
	ExpenseDate      pgtype.Date    `db:"expense_date" json:"expense_date"`
	IsReimbursement  bool           `db:"is_reimbursement" json:"is_reimbursement"`
	CreatedByID      string         `db:"created_by_id" json:"created_by_id"`
	OriginalAmount   pgtype.Int8    `db:"original_amount" json:"original_amount"`
	OriginalCurrency pgtype.Text    `db:"original_currency" json:"original_currency"`
	FxRate           pgtype.Numeric `db:"fx_rate" json:"fx_rate"`
	FxAsOf           pgtype.Date    `db:"fx_as_of" json:"fx_as_of"`
	FxSource         pgtype.Text    `db:"fx_source" json:"fx_source"`
}

type CreateExpenseRow struct {
	ID               string             `db:"id" json:"id"`
	GroupID          string             `db:"group_id" json:"group_id"`
	Title            string             `db:"title" json:"title"`
	Amount           int64              `db:"amount" json:"amount"`
	Currency         string             `db:"currency" json:"currency"`
	PaidByID         string             `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod      string             `db:"split_method" json:"split_method"`
	Category         string             `db:"category" json:"category"`
	Notes            pgtype.Text        `db:"notes" json:"notes"`
	ExpenseDate      pgtype.Date        `db:"expense_date" json:"expense_date"`
	IsReimbursement  bool               `db:"is_reimbursement" json:"is_reimbursement"`
	IsDeleted        bool               `db:"is_deleted" json:"is_deleted"`
	CreatedByID      string             `db:"created_by_id" json:"created_by_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	OriginalAmount   pgtype.Int8        `db:"original_amount" json:"original_amount"`
	OriginalCurrency pgtype.Text        `db:"original_currency" json:"original_currency"`
	FxRate           pgtype.Numeric     `db:"fx_rate" json:"fx_rate"`
	FxAsOf           pgtype.Date        `db:"fx_as_of" json:"fx_as_of"`
	FxSource         pgtype.Text        `db:"fx_source" json:"fx_source"`
}

// Explicit column list everywhere to exclude the generated `search_vector` column,
// which pgx cannot scan into interface{} cleanly.
func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (CreateExpenseRow, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.ID,
		arg.GroupID,
		arg.Title,
		arg.Amount,
		arg.Currency,
		arg.PaidByID,
		arg.SplitMethod,
		arg.Category,
		arg.Notes,
		arg.ExpenseDate,
		arg.IsReimbursement,
		arg.CreatedByID,
		arg.OriginalAmount,
		arg.OriginalCurrency,
		arg.FxRate,
		arg.FxAsOf,
		arg.FxSource,
	)
	var i CreateExpenseRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.PaidByID,
		&i.SplitMethod,
		&i.Category,
		&i.Notes,
		&i.ExpenseDate,
		&i.IsReimbursement,
		&i.IsDeleted,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalAmount,
		&i.OriginalCurrency,
		&i.FxRate,
		&i.FxAsOf,
		&i.FxSource,
	)
	return i, err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT id, group_id, title, amount, currency, paid_by_id, split_method, category, notes,
       expense_date, is_reimbursement, is_deleted, created_by_id, created_at, updated_at,
       original_amount, original_currency, fx_rate, fx_as_of, fx_source
FROM expenses WHERE id = $1 AND NOT is_deleted
`

type GetExpenseByIDRow struct {
	ID               string             `db:"id" json:"id"`
	GroupID          string             `db:"group_id" json:"group_id"`
	Title            string             `db:"title" json:"title"`
	Amount           int64              `db:"amount" json:"amount"`
	Currency         string             `db:"currency" json:"currency"`
	PaidByID         string             `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod      string             `db:"split_method" json:"split_method"`
	Category         string             `db:"category" json:"category"`
	Notes            pgtype.Text        `db:"notes" json:"notes"`
	ExpenseDate      pgtype.Date        `db:"expense_date" json:"expense_date"`
	IsReimbursement  bool               `db:"is_reimbursement" json:"is_reimbursement"`
	IsDeleted        bool               `db:"is_deleted" json:"is_deleted"`
	CreatedByID      string             `db:"created_by_id" json:"created_by_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	OriginalAmount   pgtype.Int8        `db:"original_amount" json:"original_amount"`
	OriginalCurrency pgtype.Text        `db:"original_currency" json:"original_currency"`
	FxRate           pgtype.Numeric     `db:"fx_rate" json:"fx_rate"`
	FxAsOf           pgtype.Date        `db:"fx_as_of" json:"fx_as_of"`
	FxSource         pgtype.Text        `db:"fx_source" json:"fx_source"`
}

func (q *Queries) GetExpenseByID(ctx context.Context, id string) (GetExpenseByIDRow, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, id)
	var i GetExpenseByIDRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.PaidByID,
		&i.SplitMethod,
		&i.Category,
		&i.Notes,
		&i.ExpenseDate,
		&i.IsReimbursement,
		&i.IsDeleted,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalAmount,
		&i.OriginalCurrency,
		&i.FxRate,
		&i.FxAsOf,
		&i.FxSource,
	)
	return i, err
}

const getExpenseByIDAndGroup = `-- name: GetExpenseByIDAndGroup :one
SELECT id, group_id, title, amount, currency, paid_by_id, split_method, category, notes,
       expense_date, is_reimbursement, is_deleted, created_by_id, created_at, updated_at,
       original_amount, original_currency, fx_rate, fx_as_of, fx_source
FROM expenses WHERE id = $1 AND group_id = $2 AND NOT is_deleted
`

type GetExpenseByIDAndGroupParams struct {
	ID      string `db:"id" json:"id"`
	GroupID string `db:"group_id" json:"group_id"`
}

type GetExpenseByIDAndGroupRow struct {
	ID               string             `db:"id" json:"id"`
	GroupID          string             `db:"group_id" json:"group_id"`
	Title            string             `db:"title" json:"title"`
	Amount           int64              `db:"amount" json:"amount"`
	Currency         string             `db:"currency" json:"currency"`
	PaidByID         string             `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod      string             `db:"split_method" json:"split_method"`
	Category         string             `db:"category" json:"category"`
	Notes            pgtype.Text        `db:"notes" json:"notes"`
	ExpenseDate      pgtype.Date        `db:"expense_date" json:"expense_date"`
	IsReimbursement  bool               `db:"is_reimbursement" json:"is_reimbursement"`
	IsDeleted        bool               `db:"is_deleted" json:"is_deleted"`
	CreatedByID      string             `db:"created_by_id" json:"created_by_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	OriginalAmount   pgtype.Int8        `db:"original_amount" json:"original_amount"`
	OriginalCurrency pgtype.Text        `db:"original_currency" json:"original_currency"`
	FxRate           pgtype.Numeric     `db:"fx_rate" json:"fx_rate"`
	FxAsOf           pgtype.Date        `db:"fx_as_of" json:"fx_as_of"`
	FxSource         pgtype.Text        `db:"fx_source" json:"fx_source"`
}

func (q *Queries) GetExpenseByIDAndGroup(ctx context.Context, arg GetExpenseByIDAndGroupParams) (GetExpenseByIDAndGroupRow, error) {
	row := q.db.QueryRow(ctx, getExpenseByIDAndGroup, arg.ID, arg.GroupID)
	var i GetExpenseByIDAndGroupRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.PaidByID,
		&i.SplitMethod,
		&i.Category,
		&i.Notes,
		&i.ExpenseDate,
		&i.IsReimbursement,
		&i.IsDeleted,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalAmount,
		&i.OriginalCurrency,
		&i.FxRate,
		&i.FxAsOf,
		&i.FxSource,
	)
	return i, err
}

const listExpensesByGroup = `-- name: ListExpensesByGroup :many
SELECT id, group_id, title, amount, currency, paid_by_id, split_method, category, notes,
       expense_date, is_reimbursement, is_deleted, created_by_id, created_at, updated_at,
       original_amount, original_currency, fx_rate, fx_as_of, fx_source
FROM expenses
WHERE group_id = $1 AND NOT is_deleted
ORDER BY expense_date DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListExpensesByGroupParams struct {
	GroupID string `db:"group_id" json:"group_id"`
	Limit   int32  `db:"limit" json:"limit"`
	Offset  int32  `db:"offset" json:"offset"`
}

type ListExpensesByGroupRow struct {
	ID               string             `db:"id" json:"id"`
	GroupID          string             `db:"group_id" json:"group_id"`
	Title            string             `db:"title" json:"title"`
	Amount           int64              `db:"amount" json:"amount"`
	Currency         string             `db:"currency" json:"currency"`
	PaidByID         string             `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod      string             `db:"split_method" json:"split_method"`
	Category         string             `db:"category" json:"category"`
	Notes            pgtype.Text        `db:"notes" json:"notes"`
	ExpenseDate      pgtype.Date        `db:"expense_date" json:"expense_date"`
	IsReimbursement  bool               `db:"is_reimbursement" json:"is_reimbursement"`
	IsDeleted        bool               `db:"is_deleted" json:"is_deleted"`
	CreatedByID      string             `db:"created_by_id" json:"created_by_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	OriginalAmount   pgtype.Int8        `db:"original_amount" json:"original_amount"`
	OriginalCurrency pgtype.Text        `db:"original_currency" json:"original_currency"`
	FxRate           pgtype.Numeric     `db:"fx_rate" json:"fx_rate"`
	FxAsOf           pgtype.Date        `db:"fx_as_of" json:"fx_as_of"`
	FxSource         pgtype.Text        `db:"fx_source" json:"fx_source"`
}

func (q *Queries) ListExpensesByGroup(ctx context.Context, arg ListExpensesByGroupParams) ([]ListExpensesByGroupRow, error) {
	rows, err := q.db.Query(ctx, listExpensesByGroup, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpensesByGroupRow{}
	for rows.Next() {
		var i ListExpensesByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Title,
			&i.Amount,
			&i.Currency,
			&i.PaidByID,
			&i.SplitMethod,
			&i.Category,
			&i.Notes,
			&i.ExpenseDate,
			&i.IsReimbursement,
			&i.IsDeleted,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalAmount,
			&i.OriginalCurrency,
			&i.FxRate,
			&i.FxAsOf,
			&i.FxSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchExpenses = `-- name: SearchExpenses :many
SELECT id, group_id, title, amount, currency, paid_by_id, split_method, category, notes,
       expense_date, is_reimbursement, is_deleted, created_by_id, created_at, updated_at,
       original_amount, original_currency, fx_rate, fx_as_of, fx_source
FROM expenses
WHERE group_id = $1
  AND NOT is_deleted
  AND search_vector @@ plainto_tsquery('simple', $2)
ORDER BY ts_rank(search_vector, plainto_tsquery('simple', $2)) DESC
LIMIT 50
`

type SearchExpensesParams struct {
	GroupID        string `db:"group_id" json:"group_id"`
	PlaintoTsquery string `db:"plainto_tsquery" json:"plainto_tsquery"`
}

type SearchExpensesRow struct {
	ID               string             `db:"id" json:"id"`
	GroupID          string             `db:"group_id" json:"group_id"`
	Title            string             `db:"title" json:"title"`
	Amount           int64              `db:"amount" json:"amount"`
	Currency         string             `db:"currency" json:"currency"`
	PaidByID         string             `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod      string             `db:"split_method" json:"split_method"`
	Category         string             `db:"category" json:"category"`
	Notes            pgtype.Text        `db:"notes" json:"notes"`
	ExpenseDate      pgtype.Date        `db:"expense_date" json:"expense_date"`
	IsReimbursement  bool               `db:"is_reimbursement" json:"is_reimbursement"`
	IsDeleted        bool               `db:"is_deleted" json:"is_deleted"`
	CreatedByID      string             `db:"created_by_id" json:"created_by_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	OriginalAmount   pgtype.Int8        `db:"original_amount" json:"original_amount"`
	OriginalCurrency pgtype.Text        `db:"original_currency" json:"original_currency"`
	FxRate           pgtype.Numeric     `db:"fx_rate" json:"fx_rate"`
	FxAsOf           pgtype.Date        `db:"fx_as_of" json:"fx_as_of"`
	FxSource         pgtype.Text        `db:"fx_source" json:"fx_source"`
}

func (q *Queries) SearchExpenses(ctx context.Context, arg SearchExpensesParams) ([]SearchExpensesRow, error) {
	rows, err := q.db.Query(ctx, searchExpenses, arg.GroupID, arg.PlaintoTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchExpensesRow{}
	for rows.Next() {
		var i SearchExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Title,
			&i.Amount,
			&i.Currency,
			&i.PaidByID,
			&i.SplitMethod,
			&i.Category,
			&i.Notes,
			&i.ExpenseDate,
			&i.IsReimbursement,
			&i.IsDeleted,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OriginalAmount,
			&i.OriginalCurrency,
			&i.FxRate,
			&i.FxAsOf,
			&i.FxSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteExpense = `-- name: SoftDeleteExpense :exec
UPDATE expenses SET is_deleted = TRUE, updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteExpense(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteExpense, id)
	return err
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET title        = COALESCE($2, title),
    amount       = COALESCE($3, amount),
    currency     = COALESCE($4, currency),
    paid_by_id   = COALESCE($5, paid_by_id),
    split_method = COALESCE($6, split_method),
    category     = COALESCE($7, category),
    notes        = COALESCE($8, notes),
    expense_date = COALESCE($9, expense_date),
    updated_at   = NOW()
WHERE id = $1
RETURNING id, group_id, title, amount, currency, paid_by_id, split_method, category, notes,
          expense_date, is_reimbursement, is_deleted, created_by_id, created_at, updated_at,
          original_amount, original_currency, fx_rate, fx_as_of, fx_source
`

type UpdateExpenseParams struct {
	ID          string      `db:"id" json:"id"`
	Title       pgtype.Text `db:"title" json:"title"`
	Amount      pgtype.Int8 `db:"amount" json:"amount"`
	Currency    pgtype.Text `db:"currency" json:"currency"`
	PaidByID    pgtype.Text `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod pgtype.Text `db:"split_method" json:"split_method"`
	Category    pgtype.Text `db:"category" json:"category"`
	Notes       pgtype.Text `db:"notes" json:"notes"`
	ExpenseDate pgtype.Date `db:"expense_date" json:"expense_date"`
}

type UpdateExpenseRow struct {
	ID               string             `db:"id" json:"id"`
	GroupID          string             `db:"group_id" json:"group_id"`
	Title            string             `db:"title" json:"title"`
	Amount           int64              `db:"amount" json:"amount"`
	Currency         string             `db:"currency" json:"currency"`
	PaidByID         string             `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod      string             `db:"split_method" json:"split_method"`
	Category         string             `db:"category" json:"category"`
	Notes            pgtype.Text        `db:"notes" json:"notes"`
	ExpenseDate      pgtype.Date        `db:"expense_date" json:"expense_date"`
	IsReimbursement  bool               `db:"is_reimbursement" json:"is_reimbursement"`
	IsDeleted        bool               `db:"is_deleted" json:"is_deleted"`
	CreatedByID      string             `db:"created_by_id" json:"created_by_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	OriginalAmount   pgtype.Int8        `db:"original_amount" json:"original_amount"`
	OriginalCurrency pgtype.Text        `db:"original_currency" json:"original_currency"`
	FxRate           pgtype.Numeric     `db:"fx_rate" json:"fx_rate"`
	FxAsOf           pgtype.Date        `db:"fx_as_of" json:"fx_as_of"`
	FxSource         pgtype.Text        `db:"fx_source" json:"fx_source"`
}

// NOTE: fx columns (original_amount, original_currency, fx_rate, fx_as_of,
// fx_source) are intentionally not editable via this query — change-amount or
// change-currency edits will leave the original snapshot pointing at the
// old conversion. The simpler v1 behaviour is to require a delete+recreate
// for foreign-currency expenses; a follow-up can plumb fx recomputation.
func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (UpdateExpenseRow, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.Title,
		arg.Amount,
		arg.Currency,
		arg.PaidByID,
		arg.SplitMethod,
		arg.Category,
		arg.Notes,
		arg.ExpenseDate,
	)
	var i UpdateExpenseRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.PaidByID,
		&i.SplitMethod,
		&i.Category,
		&i.Notes,
		&i.ExpenseDate,
		&i.IsReimbursement,
		&i.IsDeleted,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalAmount,
		&i.OriginalCurrency,
		&i.FxRate,
		&i.FxAsOf,
		&i.FxSource,
	)
	return i, err
}

const updateExpenseFxSnapshot = `-- name: UpdateExpenseFxSnapshot :one
UPDATE expenses
SET amount            = $2,
    original_amount   = $3,
    original_currency = $4,
    fx_rate           = $5,
    fx_as_of          = $6,
    fx_source         = $7,
    updated_at        = NOW()
WHERE id = $1
RETURNING id, group_id, title, amount, currency, paid_by_id, split_method, category, notes,
          expense_date, is_reimbursement, is_deleted, created_by_id, created_at, updated_at,
          original_amount, original_currency, fx_rate, fx_as_of, fx_source
`

type UpdateExpenseFxSnapshotParams struct {
	ID               string         `db:"id" json:"id"`
	Amount           int64          `db:"amount" json:"amount"`
	OriginalAmount   pgtype.Int8    `db:"original_amount" json:"original_amount"`
	OriginalCurrency pgtype.Text    `db:"original_currency" json:"original_currency"`
	FxRate           pgtype.Numeric `db:"fx_rate" json:"fx_rate"`
	FxAsOf           pgtype.Date    `db:"fx_as_of" json:"fx_as_of"`
	FxSource         pgtype.Text    `db:"fx_source" json:"fx_source"`
}

type UpdateExpenseFxSnapshotRow struct {
	ID               string             `db:"id" json:"id"`
	GroupID          string             `db:"group_id" json:"group_id"`
	Title            string             `db:"title" json:"title"`
	Amount           int64              `db:"amount" json:"amount"`
	Currency         string             `db:"currency" json:"currency"`
	PaidByID         string             `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod      string             `db:"split_method" json:"split_method"`
	Category         string             `db:"category" json:"category"`
	Notes            pgtype.Text        `db:"notes" json:"notes"`
	ExpenseDate      pgtype.Date        `db:"expense_date" json:"expense_date"`
	IsReimbursement  bool               `db:"is_reimbursement" json:"is_reimbursement"`
	IsDeleted        bool               `db:"is_deleted" json:"is_deleted"`
	CreatedByID      string             `db:"created_by_id" json:"created_by_id"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	OriginalAmount   pgtype.Int8        `db:"original_amount" json:"original_amount"`
	OriginalCurrency pgtype.Text        `db:"original_currency" json:"original_currency"`
	FxRate           pgtype.Numeric     `db:"fx_rate" json:"fx_rate"`
	FxAsOf           pgtype.Date        `db:"fx_as_of" json:"fx_as_of"`
	FxSource         pgtype.Text        `db:"fx_source" json:"fx_source"`
}

// Explicitly sets the FX snapshot columns and the canonical amount. The
// regular UpdateExpense query uses COALESCE narg semantics which cannot
// *clear* these columns to NULL; this query exists so the handler can
// recompute FX on edits and clear the snapshot when the new currency
// equals the group currency.
func (q *Queries) UpdateExpenseFxSnapshot(ctx context.Context, arg UpdateExpenseFxSnapshotParams) (UpdateExpenseFxSnapshotRow, error) {
	row := q.db.QueryRow(ctx, updateExpenseFxSnapshot,
		arg.ID,
		arg.Amount,
		arg.OriginalAmount,
		arg.OriginalCurrency,
		arg.FxRate,
		arg.FxAsOf,
		arg.FxSource,
	)
	var i UpdateExpenseFxSnapshotRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.PaidByID,
		&i.SplitMethod,
		&i.Category,
		&i.Notes,
		&i.ExpenseDate,
		&i.IsReimbursement,
		&i.IsDeleted,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalAmount,
		&i.OriginalCurrency,
		&i.FxRate,
		&i.FxAsOf,
		&i.FxSource,
	)
	return i, err
}
