// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: expense_splits.sql

package db

import (
	"context"
)

const createExpenseSplit = `-- name: CreateExpenseSplit :one
INSERT INTO expense_splits (id, expense_id, member_id, share)
VALUES ($1, $2, $3, $4)
RETURNING id, expense_id, member_id, share
`

type CreateExpenseSplitParams struct {
	ID        string `db:"id" json:"id"`
	ExpenseID string `db:"expense_id" json:"expense_id"`
	MemberID  string `db:"member_id" json:"member_id"`
	Share     int64  `db:"share" json:"share"`
}

func (q *Queries) CreateExpenseSplit(ctx context.Context, arg CreateExpenseSplitParams) (ExpenseSplit, error) {
	row := q.db.QueryRow(ctx, createExpenseSplit,
		arg.ID,
		arg.ExpenseID,
		arg.MemberID,
		arg.Share,
	)
	var i ExpenseSplit
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.MemberID,
		&i.Share,
	)
	return i, err
}

const deleteSplitsByExpense = `-- name: DeleteSplitsByExpense :exec
DELETE FROM expense_splits WHERE expense_id = $1
`

func (q *Queries) DeleteSplitsByExpense(ctx context.Context, expenseID string) error {
	_, err := q.db.Exec(ctx, deleteSplitsByExpense, expenseID)
	return err
}

const listSplitsByExpense = `-- name: ListSplitsByExpense :many
SELECT id, expense_id, member_id, share FROM expense_splits WHERE expense_id = $1
`

func (q *Queries) ListSplitsByExpense(ctx context.Context, expenseID string) ([]ExpenseSplit, error) {
	rows, err := q.db.Query(ctx, listSplitsByExpense, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseSplit{}
	for rows.Next() {
		var i ExpenseSplit
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.MemberID,
			&i.Share,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSplitsByGroup = `-- name: ListSplitsByGroup :many
SELECT es.id, es.expense_id, es.member_id, es.share
FROM expense_splits es
JOIN expenses e ON e.id = es.expense_id
WHERE e.group_id = $1 AND NOT e.is_deleted
`

func (q *Queries) ListSplitsByGroup(ctx context.Context, groupID string) ([]ExpenseSplit, error) {
	rows, err := q.db.Query(ctx, listSplitsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseSplit{}
	for rows.Next() {
		var i ExpenseSplit
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.MemberID,
			&i.Share,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
