// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: expenses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one

INSERT INTO expenses (id, group_id, title, amount, currency, paid_by_id, split_method, category, notes, expense_date, is_reimbursement, created_by_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, group_id, title, amount, currency, paid_by_id, split_method, category, notes, expense_date, is_reimbursement, is_deleted, created_by_id, created_at, updated_at
`

type CreateExpenseParams struct {
	ID              string      `db:"id" json:"id"`
	GroupID         string      `db:"group_id" json:"group_id"`
	Title           string      `db:"title" json:"title"`
	Amount          int64       `db:"amount" json:"amount"`
	Currency        string      `db:"currency" json:"currency"`
	PaidByID        string      `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod     string      `db:"split_method" json:"split_method"`
	Category        string      `db:"category" json:"category"`
	Notes           pgtype.Text `db:"notes" json:"notes"`
	ExpenseDate     pgtype.Date `db:"expense_date" json:"expense_date"`
	IsReimbursement bool        `db:"is_reimbursement" json:"is_reimbursement"`
	CreatedByID     string      `db:"created_by_id" json:"created_by_id"`
}

type CreateExpenseRow struct {
	ID              string             `db:"id" json:"id"`
	GroupID         string             `db:"group_id" json:"group_id"`
	Title           string             `db:"title" json:"title"`
	Amount          int64              `db:"amount" json:"amount"`
	Currency        string             `db:"currency" json:"currency"`
	PaidByID        string             `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod     string             `db:"split_method" json:"split_method"`
	Category        string             `db:"category" json:"category"`
	Notes           pgtype.Text        `db:"notes" json:"notes"`
	ExpenseDate     pgtype.Date        `db:"expense_date" json:"expense_date"`
	IsReimbursement bool               `db:"is_reimbursement" json:"is_reimbursement"`
	IsDeleted       bool               `db:"is_deleted" json:"is_deleted"`
	CreatedByID     string             `db:"created_by_id" json:"created_by_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

// Explicit column list everywhere to exclude the generated `search_vector` column,
// which pgx cannot scan into interface{} cleanly.
func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (CreateExpenseRow, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.ID,
		arg.GroupID,
		arg.Title,
		arg.Amount,
		arg.Currency,
		arg.PaidByID,
		arg.SplitMethod,
		arg.Category,
		arg.Notes,
		arg.ExpenseDate,
		arg.IsReimbursement,
		arg.CreatedByID,
	)
	var i CreateExpenseRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.PaidByID,
		&i.SplitMethod,
		&i.Category,
		&i.Notes,
		&i.ExpenseDate,
		&i.IsReimbursement,
		&i.IsDeleted,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT id, group_id, title, amount, currency, paid_by_id, split_method, category, notes, expense_date, is_reimbursement, is_deleted, created_by_id, created_at, updated_at
FROM expenses WHERE id = $1 AND NOT is_deleted
`

type GetExpenseByIDRow struct {
	ID              string             `db:"id" json:"id"`
	GroupID         string             `db:"group_id" json:"group_id"`
	Title           string             `db:"title" json:"title"`
	Amount          int64              `db:"amount" json:"amount"`
	Currency        string             `db:"currency" json:"currency"`
	PaidByID        string             `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod     string             `db:"split_method" json:"split_method"`
	Category        string             `db:"category" json:"category"`
	Notes           pgtype.Text        `db:"notes" json:"notes"`
	ExpenseDate     pgtype.Date        `db:"expense_date" json:"expense_date"`
	IsReimbursement bool               `db:"is_reimbursement" json:"is_reimbursement"`
	IsDeleted       bool               `db:"is_deleted" json:"is_deleted"`
	CreatedByID     string             `db:"created_by_id" json:"created_by_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetExpenseByID(ctx context.Context, id string) (GetExpenseByIDRow, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, id)
	var i GetExpenseByIDRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.PaidByID,
		&i.SplitMethod,
		&i.Category,
		&i.Notes,
		&i.ExpenseDate,
		&i.IsReimbursement,
		&i.IsDeleted,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExpenseByIDAndGroup = `-- name: GetExpenseByIDAndGroup :one
SELECT id, group_id, title, amount, currency, paid_by_id, split_method, category, notes, expense_date, is_reimbursement, is_deleted, created_by_id, created_at, updated_at
FROM expenses WHERE id = $1 AND group_id = $2 AND NOT is_deleted
`

type GetExpenseByIDAndGroupParams struct {
	ID      string `db:"id" json:"id"`
	GroupID string `db:"group_id" json:"group_id"`
}

type GetExpenseByIDAndGroupRow struct {
	ID              string             `db:"id" json:"id"`
	GroupID         string             `db:"group_id" json:"group_id"`
	Title           string             `db:"title" json:"title"`
	Amount          int64              `db:"amount" json:"amount"`
	Currency        string             `db:"currency" json:"currency"`
	PaidByID        string             `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod     string             `db:"split_method" json:"split_method"`
	Category        string             `db:"category" json:"category"`
	Notes           pgtype.Text        `db:"notes" json:"notes"`
	ExpenseDate     pgtype.Date        `db:"expense_date" json:"expense_date"`
	IsReimbursement bool               `db:"is_reimbursement" json:"is_reimbursement"`
	IsDeleted       bool               `db:"is_deleted" json:"is_deleted"`
	CreatedByID     string             `db:"created_by_id" json:"created_by_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetExpenseByIDAndGroup(ctx context.Context, arg GetExpenseByIDAndGroupParams) (GetExpenseByIDAndGroupRow, error) {
	row := q.db.QueryRow(ctx, getExpenseByIDAndGroup, arg.ID, arg.GroupID)
	var i GetExpenseByIDAndGroupRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.PaidByID,
		&i.SplitMethod,
		&i.Category,
		&i.Notes,
		&i.ExpenseDate,
		&i.IsReimbursement,
		&i.IsDeleted,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpensesByGroup = `-- name: ListExpensesByGroup :many
SELECT id, group_id, title, amount, currency, paid_by_id, split_method, category, notes, expense_date, is_reimbursement, is_deleted, created_by_id, created_at, updated_at
FROM expenses
WHERE group_id = $1 AND NOT is_deleted
ORDER BY expense_date DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListExpensesByGroupParams struct {
	GroupID string `db:"group_id" json:"group_id"`
	Limit   int32  `db:"limit" json:"limit"`
	Offset  int32  `db:"offset" json:"offset"`
}

type ListExpensesByGroupRow struct {
	ID              string             `db:"id" json:"id"`
	GroupID         string             `db:"group_id" json:"group_id"`
	Title           string             `db:"title" json:"title"`
	Amount          int64              `db:"amount" json:"amount"`
	Currency        string             `db:"currency" json:"currency"`
	PaidByID        string             `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod     string             `db:"split_method" json:"split_method"`
	Category        string             `db:"category" json:"category"`
	Notes           pgtype.Text        `db:"notes" json:"notes"`
	ExpenseDate     pgtype.Date        `db:"expense_date" json:"expense_date"`
	IsReimbursement bool               `db:"is_reimbursement" json:"is_reimbursement"`
	IsDeleted       bool               `db:"is_deleted" json:"is_deleted"`
	CreatedByID     string             `db:"created_by_id" json:"created_by_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) ListExpensesByGroup(ctx context.Context, arg ListExpensesByGroupParams) ([]ListExpensesByGroupRow, error) {
	rows, err := q.db.Query(ctx, listExpensesByGroup, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpensesByGroupRow{}
	for rows.Next() {
		var i ListExpensesByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Title,
			&i.Amount,
			&i.Currency,
			&i.PaidByID,
			&i.SplitMethod,
			&i.Category,
			&i.Notes,
			&i.ExpenseDate,
			&i.IsReimbursement,
			&i.IsDeleted,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchExpenses = `-- name: SearchExpenses :many
SELECT id, group_id, title, amount, currency, paid_by_id, split_method, category, notes, expense_date, is_reimbursement, is_deleted, created_by_id, created_at, updated_at
FROM expenses
WHERE group_id = $1
  AND NOT is_deleted
  AND search_vector @@ plainto_tsquery('simple', $2)
ORDER BY ts_rank(search_vector, plainto_tsquery('simple', $2)) DESC
LIMIT 50
`

type SearchExpensesParams struct {
	GroupID        string `db:"group_id" json:"group_id"`
	PlaintoTsquery string `db:"plainto_tsquery" json:"plainto_tsquery"`
}

type SearchExpensesRow struct {
	ID              string             `db:"id" json:"id"`
	GroupID         string             `db:"group_id" json:"group_id"`
	Title           string             `db:"title" json:"title"`
	Amount          int64              `db:"amount" json:"amount"`
	Currency        string             `db:"currency" json:"currency"`
	PaidByID        string             `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod     string             `db:"split_method" json:"split_method"`
	Category        string             `db:"category" json:"category"`
	Notes           pgtype.Text        `db:"notes" json:"notes"`
	ExpenseDate     pgtype.Date        `db:"expense_date" json:"expense_date"`
	IsReimbursement bool               `db:"is_reimbursement" json:"is_reimbursement"`
	IsDeleted       bool               `db:"is_deleted" json:"is_deleted"`
	CreatedByID     string             `db:"created_by_id" json:"created_by_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) SearchExpenses(ctx context.Context, arg SearchExpensesParams) ([]SearchExpensesRow, error) {
	rows, err := q.db.Query(ctx, searchExpenses, arg.GroupID, arg.PlaintoTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchExpensesRow{}
	for rows.Next() {
		var i SearchExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Title,
			&i.Amount,
			&i.Currency,
			&i.PaidByID,
			&i.SplitMethod,
			&i.Category,
			&i.Notes,
			&i.ExpenseDate,
			&i.IsReimbursement,
			&i.IsDeleted,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteExpense = `-- name: SoftDeleteExpense :exec
UPDATE expenses SET is_deleted = TRUE, updated_at = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteExpense(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteExpense, id)
	return err
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET title        = COALESCE($2, title),
    amount       = COALESCE($3, amount),
    currency     = COALESCE($4, currency),
    paid_by_id   = COALESCE($5, paid_by_id),
    split_method = COALESCE($6, split_method),
    category     = COALESCE($7, category),
    notes        = COALESCE($8, notes),
    expense_date = COALESCE($9, expense_date),
    updated_at   = NOW()
WHERE id = $1
RETURNING id, group_id, title, amount, currency, paid_by_id, split_method, category, notes, expense_date, is_reimbursement, is_deleted, created_by_id, created_at, updated_at
`

type UpdateExpenseParams struct {
	ID          string      `db:"id" json:"id"`
	Title       pgtype.Text `db:"title" json:"title"`
	Amount      pgtype.Int8 `db:"amount" json:"amount"`
	Currency    pgtype.Text `db:"currency" json:"currency"`
	PaidByID    pgtype.Text `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod pgtype.Text `db:"split_method" json:"split_method"`
	Category    pgtype.Text `db:"category" json:"category"`
	Notes       pgtype.Text `db:"notes" json:"notes"`
	ExpenseDate pgtype.Date `db:"expense_date" json:"expense_date"`
}

type UpdateExpenseRow struct {
	ID              string             `db:"id" json:"id"`
	GroupID         string             `db:"group_id" json:"group_id"`
	Title           string             `db:"title" json:"title"`
	Amount          int64              `db:"amount" json:"amount"`
	Currency        string             `db:"currency" json:"currency"`
	PaidByID        string             `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod     string             `db:"split_method" json:"split_method"`
	Category        string             `db:"category" json:"category"`
	Notes           pgtype.Text        `db:"notes" json:"notes"`
	ExpenseDate     pgtype.Date        `db:"expense_date" json:"expense_date"`
	IsReimbursement bool               `db:"is_reimbursement" json:"is_reimbursement"`
	IsDeleted       bool               `db:"is_deleted" json:"is_deleted"`
	CreatedByID     string             `db:"created_by_id" json:"created_by_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (UpdateExpenseRow, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.Title,
		arg.Amount,
		arg.Currency,
		arg.PaidByID,
		arg.SplitMethod,
		arg.Category,
		arg.Notes,
		arg.ExpenseDate,
	)
	var i UpdateExpenseRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Amount,
		&i.Currency,
		&i.PaidByID,
		&i.SplitMethod,
		&i.Category,
		&i.Notes,
		&i.ExpenseDate,
		&i.IsReimbursement,
		&i.IsDeleted,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
