// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: expense_attachments.sql

package db

import (
	"context"
)

const createExpenseAttachment = `-- name: CreateExpenseAttachment :one
INSERT INTO expense_attachments (id, expense_id, s3_key, mime_type, size_bytes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, expense_id, s3_key, mime_type, size_bytes, created_at
`

type CreateExpenseAttachmentParams struct {
	ID        string `db:"id" json:"id"`
	ExpenseID string `db:"expense_id" json:"expense_id"`
	S3Key     string `db:"s3_key" json:"s3_key"`
	MimeType  string `db:"mime_type" json:"mime_type"`
	SizeBytes int64  `db:"size_bytes" json:"size_bytes"`
}

func (q *Queries) CreateExpenseAttachment(ctx context.Context, arg CreateExpenseAttachmentParams) (ExpenseAttachment, error) {
	row := q.db.QueryRow(ctx, createExpenseAttachment,
		arg.ID,
		arg.ExpenseID,
		arg.S3Key,
		arg.MimeType,
		arg.SizeBytes,
	)
	var i ExpenseAttachment
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.S3Key,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM expense_attachments WHERE id = $1
`

func (q *Queries) DeleteAttachment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAttachment, id)
	return err
}

const deleteAttachmentsByExpense = `-- name: DeleteAttachmentsByExpense :exec
DELETE FROM expense_attachments WHERE expense_id = $1
`

func (q *Queries) DeleteAttachmentsByExpense(ctx context.Context, expenseID string) error {
	_, err := q.db.Exec(ctx, deleteAttachmentsByExpense, expenseID)
	return err
}

const getExpenseAttachment = `-- name: GetExpenseAttachment :one
SELECT id, expense_id, s3_key, mime_type, size_bytes, created_at FROM expense_attachments WHERE id = $1
`

func (q *Queries) GetExpenseAttachment(ctx context.Context, id string) (ExpenseAttachment, error) {
	row := q.db.QueryRow(ctx, getExpenseAttachment, id)
	var i ExpenseAttachment
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.S3Key,
		&i.MimeType,
		&i.SizeBytes,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentsByExpense = `-- name: ListAttachmentsByExpense :many
SELECT id, expense_id, s3_key, mime_type, size_bytes, created_at FROM expense_attachments WHERE expense_id = $1
`

func (q *Queries) ListAttachmentsByExpense(ctx context.Context, expenseID string) ([]ExpenseAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByExpense, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseAttachment{}
	for rows.Next() {
		var i ExpenseAttachment
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.S3Key,
			&i.MimeType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
