// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: feedback_reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFeedbackReport = `-- name: CreateFeedbackReport :one

INSERT INTO feedback_reports (id, user_id, kind, body, app_version, platform, locale)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, kind, body, app_version, platform, locale, created_at
`

type CreateFeedbackReportParams struct {
	ID         string      `db:"id" json:"id"`
	UserID     string      `db:"user_id" json:"user_id"`
	Kind       string      `db:"kind" json:"kind"`
	Body       string      `db:"body" json:"body"`
	AppVersion pgtype.Text `db:"app_version" json:"app_version"`
	Platform   pgtype.Text `db:"platform" json:"platform"`
	Locale     pgtype.Text `db:"locale" json:"locale"`
}

// feedback_reports: bug reports and feature ideas from the in-app feedback
// screen. Write-only from the app's point of view.
// One row per submission. Deliberately not deduplicated: two reports with the
// same text minutes apart usually mean the user hit the bug twice, which is
// itself a signal.
func (q *Queries) CreateFeedbackReport(ctx context.Context, arg CreateFeedbackReportParams) (FeedbackReport, error) {
	row := q.db.QueryRow(ctx, createFeedbackReport,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Body,
		arg.AppVersion,
		arg.Platform,
		arg.Locale,
	)
	var i FeedbackReport
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Body,
		&i.AppVersion,
		&i.Platform,
		&i.Locale,
		&i.CreatedAt,
	)
	return i, err
}
