// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: fx_rates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getClosestFxRate = `-- name: GetClosestFxRate :one
SELECT base, quote, rate, as_of, source, created_at
FROM fx_rates
WHERE base = $1 AND quote = $2
ORDER BY ABS(as_of - $3) ASC, as_of DESC
LIMIT 1
`

type GetClosestFxRateParams struct {
	Base  string      `db:"base" json:"base"`
	Quote string      `db:"quote" json:"quote"`
	AsOf  pgtype.Date `db:"as_of" json:"as_of"`
}

// Rate whose as_of is closest to the requested date, in either direction.
// This is the only lookup used by Convert; it gracefully handles
// weekends/holidays (no rate that day → picks the nearest business day)
// and historical receipts older than our oldest snapshot (no rate before
// that day → picks the freshest forward rate). The actual date used is
// always returned to the caller for audit display.
func (q *Queries) GetClosestFxRate(ctx context.Context, arg GetClosestFxRateParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, getClosestFxRate, arg.Base, arg.Quote, arg.AsOf)
	var i FxRate
	err := row.Scan(
		&i.Base,
		&i.Quote,
		&i.Rate,
		&i.AsOf,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const getFxRate = `-- name: GetFxRate :one
SELECT base, quote, rate, as_of, source, created_at
FROM fx_rates
WHERE base = $1 AND quote = $2 AND as_of = $3
`

type GetFxRateParams struct {
	Base  string      `db:"base" json:"base"`
	Quote string      `db:"quote" json:"quote"`
	AsOf  pgtype.Date `db:"as_of" json:"as_of"`
}

// Look up a single rate. For cross conversions (base ≠ stored base) callers
// compose two lookups: get(EUR,HUF,d) and get(EUR,SEK,d), then divide.
func (q *Queries) GetFxRate(ctx context.Context, arg GetFxRateParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, getFxRate, arg.Base, arg.Quote, arg.AsOf)
	var i FxRate
	err := row.Scan(
		&i.Base,
		&i.Quote,
		&i.Rate,
		&i.AsOf,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const latestFxAsOf = `-- name: LatestFxAsOf :one
SELECT MAX(as_of)::date AS as_of
FROM fx_rates
WHERE base = $1
`

// Most recent as_of present in the table for a given base. Lets callers
// ask "what's the freshest day we have rates for?" without specifying a
// target date.
func (q *Queries) LatestFxAsOf(ctx context.Context, base string) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, latestFxAsOf, base)
	var as_of pgtype.Date
	err := row.Scan(&as_of)
	return as_of, err
}

const listFxRatesForDate = `-- name: ListFxRatesForDate :many
SELECT base, quote, rate, as_of, source, created_at
FROM fx_rates
WHERE base = $1 AND as_of = $2
`

type ListFxRatesForDateParams struct {
	Base string      `db:"base" json:"base"`
	AsOf pgtype.Date `db:"as_of" json:"as_of"`
}

// All quotes for a given base+date — used by GET /api/fx/rates to ship the
// full daily matrix to the client in one round-trip.
func (q *Queries) ListFxRatesForDate(ctx context.Context, arg ListFxRatesForDateParams) ([]FxRate, error) {
	rows, err := q.db.Query(ctx, listFxRatesForDate, arg.Base, arg.AsOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FxRate{}
	for rows.Next() {
		var i FxRate
		if err := rows.Scan(
			&i.Base,
			&i.Quote,
			&i.Rate,
			&i.AsOf,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFxRate = `-- name: UpsertFxRate :exec
INSERT INTO fx_rates (base, quote, rate, as_of, source)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (base, quote, as_of) DO UPDATE
    SET rate = EXCLUDED.rate,
        source = EXCLUDED.source
`

type UpsertFxRateParams struct {
	Base   string         `db:"base" json:"base"`
	Quote  string         `db:"quote" json:"quote"`
	Rate   pgtype.Numeric `db:"rate" json:"rate"`
	AsOf   pgtype.Date    `db:"as_of" json:"as_of"`
	Source string         `db:"source" json:"source"`
}

// Insert or update a single (base, quote, as_of) row. Caller is responsible
// for batching when ingesting a full daily snapshot — Postgres handles
// ~30 sequential UPSERTs in well under a second.
func (q *Queries) UpsertFxRate(ctx context.Context, arg UpsertFxRateParams) error {
	_, err := q.db.Exec(ctx, upsertFxRate,
		arg.Base,
		arg.Quote,
		arg.Rate,
		arg.AsOf,
		arg.Source,
	)
	return err
}
