// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: group_members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimGhostMember = `-- name: ClaimGhostMember :one
UPDATE group_members
SET user_id  = $2,
    is_ghost = FALSE
WHERE id = $1 AND is_ghost = TRUE
RETURNING id, group_id, user_id, name, role, is_ghost, joined_at
`

type ClaimGhostMemberParams struct {
	ID     string      `db:"id" json:"id"`
	UserID pgtype.Text `db:"user_id" json:"user_id"`
}

func (q *Queries) ClaimGhostMember(ctx context.Context, arg ClaimGhostMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, claimGhostMember, arg.ID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Name,
		&i.Role,
		&i.IsGhost,
		&i.JoinedAt,
	)
	return i, err
}

const createGroupMember = `-- name: CreateGroupMember :one
INSERT INTO group_members (id, group_id, user_id, name, role, is_ghost)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, group_id, user_id, name, role, is_ghost, joined_at
`

type CreateGroupMemberParams struct {
	ID      string      `db:"id" json:"id"`
	GroupID string      `db:"group_id" json:"group_id"`
	UserID  pgtype.Text `db:"user_id" json:"user_id"`
	Name    string      `db:"name" json:"name"`
	Role    string      `db:"role" json:"role"`
	IsGhost bool        `db:"is_ghost" json:"is_ghost"`
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, createGroupMember,
		arg.ID,
		arg.GroupID,
		arg.UserID,
		arg.Name,
		arg.Role,
		arg.IsGhost,
	)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Name,
		&i.Role,
		&i.IsGhost,
		&i.JoinedAt,
	)
	return i, err
}

const deleteGroupMember = `-- name: DeleteGroupMember :exec
DELETE FROM group_members WHERE id = $1
`

func (q *Queries) DeleteGroupMember(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteGroupMember, id)
	return err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT id, group_id, user_id, name, role, is_ghost, joined_at FROM group_members WHERE id = $1
`

func (q *Queries) GetGroupMember(ctx context.Context, id string) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMember, id)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Name,
		&i.Role,
		&i.IsGhost,
		&i.JoinedAt,
	)
	return i, err
}

const getGroupMemberByUserAndGroup = `-- name: GetGroupMemberByUserAndGroup :one
SELECT id, group_id, user_id, name, role, is_ghost, joined_at FROM group_members
WHERE group_id = $1 AND user_id = $2
`

type GetGroupMemberByUserAndGroupParams struct {
	GroupID string      `db:"group_id" json:"group_id"`
	UserID  pgtype.Text `db:"user_id" json:"user_id"`
}

func (q *Queries) GetGroupMemberByUserAndGroup(ctx context.Context, arg GetGroupMemberByUserAndGroupParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMemberByUserAndGroup, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Name,
		&i.Role,
		&i.IsGhost,
		&i.JoinedAt,
	)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT id, group_id, user_id, name, role, is_ghost, joined_at FROM group_members WHERE group_id = $1 ORDER BY joined_at ASC
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupID string) ([]GroupMember, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupMember{}
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Name,
			&i.Role,
			&i.IsGhost,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroupMemberName = `-- name: UpdateGroupMemberName :one
UPDATE group_members SET name = $2 WHERE id = $1 RETURNING id, group_id, user_id, name, role, is_ghost, joined_at
`

type UpdateGroupMemberNameParams struct {
	ID   string `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

func (q *Queries) UpdateGroupMemberName(ctx context.Context, arg UpdateGroupMemberNameParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, updateGroupMemberName, arg.ID, arg.Name)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Name,
		&i.Role,
		&i.IsGhost,
		&i.JoinedAt,
	)
	return i, err
}
