// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (id, name, currency, language, created_by, invite_token)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, currency, created_by, invite_token, is_archived, created_at, updated_at, language
`

type CreateGroupParams struct {
	ID          string `db:"id" json:"id"`
	Name        string `db:"name" json:"name"`
	Currency    string `db:"currency" json:"currency"`
	Language    string `db:"language" json:"language"`
	CreatedBy   string `db:"created_by" json:"created_by"`
	InviteToken string `db:"invite_token" json:"invite_token"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.ID,
		arg.Name,
		arg.Currency,
		arg.Language,
		arg.CreatedBy,
		arg.InviteToken,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.CreatedBy,
		&i.InviteToken,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Language,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, currency, created_by, invite_token, is_archived, created_at, updated_at, language FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.CreatedBy,
		&i.InviteToken,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Language,
	)
	return i, err
}

const getGroupByInviteToken = `-- name: GetGroupByInviteToken :one
SELECT id, name, currency, created_by, invite_token, is_archived, created_at, updated_at, language FROM groups WHERE invite_token = $1
`

func (q *Queries) GetGroupByInviteToken(ctx context.Context, inviteToken string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByInviteToken, inviteToken)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.CreatedBy,
		&i.InviteToken,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Language,
	)
	return i, err
}

const listGroupsByUserID = `-- name: ListGroupsByUserID :many
SELECT g.id, g.name, g.currency, g.created_by, g.invite_token, g.is_archived, g.created_at, g.updated_at, g.language FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = $1 AND NOT g.is_archived
ORDER BY g.updated_at DESC
`

func (q *Queries) ListGroupsByUserID(ctx context.Context, userID pgtype.Text) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Currency,
			&i.CreatedBy,
			&i.InviteToken,
			&i.IsArchived,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regenerateInviteToken = `-- name: RegenerateInviteToken :one
UPDATE groups SET invite_token = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, currency, created_by, invite_token, is_archived, created_at, updated_at, language
`

type RegenerateInviteTokenParams struct {
	ID          string `db:"id" json:"id"`
	InviteToken string `db:"invite_token" json:"invite_token"`
}

func (q *Queries) RegenerateInviteToken(ctx context.Context, arg RegenerateInviteTokenParams) (Group, error) {
	row := q.db.QueryRow(ctx, regenerateInviteToken, arg.ID, arg.InviteToken)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.CreatedBy,
		&i.InviteToken,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Language,
	)
	return i, err
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
SET name        = COALESCE($2, name),
    currency    = COALESCE($3, currency),
    language    = COALESCE($4, language),
    is_archived = COALESCE($5, is_archived),
    updated_at  = NOW()
WHERE id = $1
RETURNING id, name, currency, created_by, invite_token, is_archived, created_at, updated_at, language
`

type UpdateGroupParams struct {
	ID         string      `db:"id" json:"id"`
	Name       pgtype.Text `db:"name" json:"name"`
	Currency   pgtype.Text `db:"currency" json:"currency"`
	Language   pgtype.Text `db:"language" json:"language"`
	IsArchived pgtype.Bool `db:"is_archived" json:"is_archived"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.Name,
		arg.Currency,
		arg.Language,
		arg.IsArchived,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Currency,
		&i.CreatedBy,
		&i.InviteToken,
		&i.IsArchived,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Language,
	)
	return i, err
}
