// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID         string             `db:"id" json:"id"`
	GroupID    string             `db:"group_id" json:"group_id"`
	ActorID    string             `db:"actor_id" json:"actor_id"`
	EventType  string             `db:"event_type" json:"event_type"`
	EntityID   pgtype.Text        `db:"entity_id" json:"entity_id"`
	EntityType pgtype.Text        `db:"entity_type" json:"entity_type"`
	Payload    []byte             `db:"payload" json:"payload"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Expense struct {
	ID              string             `db:"id" json:"id"`
	GroupID         string             `db:"group_id" json:"group_id"`
	Title           string             `db:"title" json:"title"`
	Amount          int64              `db:"amount" json:"amount"`
	Currency        string             `db:"currency" json:"currency"`
	PaidByID        string             `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod     string             `db:"split_method" json:"split_method"`
	Category        string             `db:"category" json:"category"`
	Notes           pgtype.Text        `db:"notes" json:"notes"`
	ExpenseDate     pgtype.Date        `db:"expense_date" json:"expense_date"`
	IsReimbursement bool               `db:"is_reimbursement" json:"is_reimbursement"`
	IsDeleted       bool               `db:"is_deleted" json:"is_deleted"`
	CreatedByID     string             `db:"created_by_id" json:"created_by_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SearchVector    interface{}        `db:"search_vector" json:"search_vector"`
}

type ExpenseAttachment struct {
	ID        string             `db:"id" json:"id"`
	ExpenseID string             `db:"expense_id" json:"expense_id"`
	S3Key     string             `db:"s3_key" json:"s3_key"`
	MimeType  string             `db:"mime_type" json:"mime_type"`
	SizeBytes int64              `db:"size_bytes" json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ExpenseSplit struct {
	ID        string `db:"id" json:"id"`
	ExpenseID string `db:"expense_id" json:"expense_id"`
	MemberID  string `db:"member_id" json:"member_id"`
	Share     int64  `db:"share" json:"share"`
}

type Group struct {
	ID          string             `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Currency    string             `db:"currency" json:"currency"`
	CreatedBy   string             `db:"created_by" json:"created_by"`
	InviteToken string             `db:"invite_token" json:"invite_token"`
	IsArchived  bool               `db:"is_archived" json:"is_archived"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type GroupMember struct {
	ID       string             `db:"id" json:"id"`
	GroupID  string             `db:"group_id" json:"group_id"`
	UserID   pgtype.Text        `db:"user_id" json:"user_id"`
	Name     string             `db:"name" json:"name"`
	Role     string             `db:"role" json:"role"`
	IsGhost  bool               `db:"is_ghost" json:"is_ghost"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

type MagicLinkToken struct {
	ID        string             `db:"id" json:"id"`
	TokenHash string             `db:"token_hash" json:"token_hash"`
	TokenType string             `db:"token_type" json:"token_type"`
	UserID    pgtype.Text        `db:"user_id" json:"user_id"`
	Email     string             `db:"email" json:"email"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	UsedAt    pgtype.Timestamptz `db:"used_at" json:"used_at"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type MemberBalance struct {
	GroupID    string      `db:"group_id" json:"group_id"`
	MemberID   string      `db:"member_id" json:"member_id"`
	UserID     pgtype.Text `db:"user_id" json:"user_id"`
	Currency   pgtype.Text `db:"currency" json:"currency"`
	NetBalance int64       `db:"net_balance" json:"net_balance"`
}

type PushToken struct {
	ID         string             `db:"id" json:"id"`
	UserID     string             `db:"user_id" json:"user_id"`
	Token      string             `db:"token" json:"token"`
	Platform   string             `db:"platform" json:"platform"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
}

type Settlement struct {
	ID          string             `db:"id" json:"id"`
	GroupID     string             `db:"group_id" json:"group_id"`
	FromMember  string             `db:"from_member" json:"from_member"`
	ToMember    string             `db:"to_member" json:"to_member"`
	Amount      int64              `db:"amount" json:"amount"`
	Currency    string             `db:"currency" json:"currency"`
	Note        pgtype.Text        `db:"note" json:"note"`
	CreatedByID string             `db:"created_by_id" json:"created_by_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Method      string             `db:"method" json:"method"`
	ExternalRef pgtype.Text        `db:"external_ref" json:"external_ref"`
	RevertedAt  pgtype.Timestamptz `db:"reverted_at" json:"reverted_at"`
}

type User struct {
	ID          string             `db:"id" json:"id"`
	Email       string             `db:"email" json:"email"`
	DisplayName string             `db:"display_name" json:"display_name"`
	AvatarUrl   pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Phone       pgtype.Text        `db:"phone" json:"phone"`
	Locale      string             `db:"locale" json:"locale"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
