// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: nudges.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const selectNudgeDebts = `-- name: SelectNudgeDebts :many
WITH balance_change_events AS (
    SELECT
        gm.group_id,
        gm.id                                AS member_id,
        GREATEST(e.created_at, e.updated_at) AS changed_at
    FROM group_members gm
    JOIN expenses e
        ON e.group_id = gm.group_id AND NOT e.is_reimbursement
    LEFT JOIN expense_splits es
        ON es.expense_id = e.id AND es.member_id = gm.id
    WHERE gm.user_id = $1
      AND gm.group_id = $2
      AND (e.paid_by_id = gm.id OR es.member_id IS NOT NULL)

    UNION ALL

    SELECT
        gm.group_id,
        gm.id,
        GREATEST(s.created_at, COALESCE(s.reverted_at, s.created_at))
    FROM group_members gm
    JOIN settlements s
        ON s.group_id = gm.group_id
        AND (s.from_member = gm.id OR s.to_member = gm.id)
    WHERE gm.user_id = $1
      AND gm.group_id = $2
)
SELECT
    g.name                         AS group_name,
    mb.currency,
    mb.net_balance,
    lc.last_change_at::TIMESTAMPTZ AS last_balance_change_at
FROM member_balances mb
JOIN groups g ON g.id = mb.group_id
JOIN (
    SELECT group_id, member_id, MAX(changed_at) AS last_change_at
    FROM balance_change_events
    GROUP BY group_id, member_id
) lc ON lc.group_id = mb.group_id AND lc.member_id = mb.member_id
WHERE mb.user_id = $1
  AND mb.group_id = $2
  AND mb.currency IS NOT NULL
  AND mb.net_balance < 0
  AND lc.last_change_at <= NOW() - make_interval(days => $3::INT)
  AND NOT EXISTS (
      SELECT 1 FROM balance_nudges bn
      WHERE bn.user_id = $1
        AND bn.group_id = $2
        AND bn.last_nudged_at > NOW() - make_interval(days => $4::INT)
  )
ORDER BY mb.currency
`

type SelectNudgeDebtsParams struct {
	UserID     pgtype.Text `db:"user_id" json:"user_id"`
	GroupID    string      `db:"group_id" json:"group_id"`
	AfterDays  int32       `db:"after_days" json:"after_days"`
	RepeatDays int32       `db:"repeat_days" json:"repeat_days"`
}

type SelectNudgeDebtsRow struct {
	GroupName           string             `db:"group_name" json:"group_name"`
	Currency            pgtype.Text        `db:"currency" json:"currency"`
	NetBalance          int64              `db:"net_balance" json:"net_balance"`
	LastBalanceChangeAt pgtype.Timestamptz `db:"last_balance_change_at" json:"last_balance_change_at"`
}

// Fire-side eligibility re-check for one (user, group) pair. One row per
// owed currency (net_balance < 0), with the group name and the member's
// last balance change. Empty result means "no longer eligible" — the
// balance changed, was settled, or the pair was nudged inside repeat_days.
func (q *Queries) SelectNudgeDebts(ctx context.Context, arg SelectNudgeDebtsParams) ([]SelectNudgeDebtsRow, error) {
	rows, err := q.db.Query(ctx, selectNudgeDebts,
		arg.UserID,
		arg.GroupID,
		arg.AfterDays,
		arg.RepeatDays,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectNudgeDebtsRow{}
	for rows.Next() {
		var i SelectNudgeDebtsRow
		if err := rows.Scan(
			&i.GroupName,
			&i.Currency,
			&i.NetBalance,
			&i.LastBalanceChangeAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectNudgeEligiblePairs = `-- name: SelectNudgeEligiblePairs :many

WITH balance_change_events AS (
    SELECT
        gm.group_id,
        gm.id                                AS member_id,
        GREATEST(e.created_at, e.updated_at) AS changed_at
    FROM group_members gm
    JOIN expenses e
        ON e.group_id = gm.group_id AND NOT e.is_reimbursement
    LEFT JOIN expense_splits es
        ON es.expense_id = e.id AND es.member_id = gm.id
    WHERE (e.paid_by_id = gm.id OR es.member_id IS NOT NULL)

    UNION ALL

    SELECT
        gm.group_id,
        gm.id,
        GREATEST(s.created_at, COALESCE(s.reverted_at, s.created_at))
    FROM group_members gm
    JOIN settlements s
        ON s.group_id = gm.group_id
        AND (s.from_member = gm.id OR s.to_member = gm.id)
)
SELECT DISTINCT mb.user_id::TEXT AS user_id, mb.group_id
FROM member_balances mb
JOIN (
    SELECT group_id, member_id, MAX(changed_at) AS last_change_at
    FROM balance_change_events
    GROUP BY group_id, member_id
) lc ON lc.group_id = mb.group_id AND lc.member_id = mb.member_id
WHERE mb.user_id IS NOT NULL
  AND mb.currency IS NOT NULL
  AND mb.net_balance < 0
  AND lc.last_change_at <= NOW() - make_interval(days => $1::INT)
  AND EXISTS (
      SELECT 1 FROM push_tokens pt WHERE pt.user_id = mb.user_id
  )
  AND NOT EXISTS (
      SELECT 1 FROM balance_nudges bn
      WHERE bn.user_id = mb.user_id
        AND bn.group_id = mb.group_id
        AND bn.last_nudged_at > NOW() - make_interval(days => $2::INT)
  )
LIMIT $3
`

type SelectNudgeEligiblePairsParams struct {
	AfterDays  int32 `db:"after_days" json:"after_days"`
	RepeatDays int32 `db:"repeat_days" json:"repeat_days"`
	MaxPairs   int32 `db:"max_pairs" json:"max_pairs"`
}

type SelectNudgeEligiblePairsRow struct {
	UserID  string `db:"user_id" json:"user_id"`
	GroupID string `db:"group_id" json:"group_id"`
}

// Unsettled-balance nudge job. Eligibility for a (user, group) pair:
//   - the user is a debtor (net_balance < 0) in at least one currency,
//   - the member's balance hasn't changed for at least after_days days
//     (balance_change_events — same definition as in balances.sql),
//   - the user has at least one push token,
//   - the pair was never nudged, or last_nudged_at is at least repeat_days old.
//
// Cross-instance scan used by the nudge tick. Returns distinct (user, group)
// pairs to enqueue a fire job for, capped at max_pairs per tick.
func (q *Queries) SelectNudgeEligiblePairs(ctx context.Context, arg SelectNudgeEligiblePairsParams) ([]SelectNudgeEligiblePairsRow, error) {
	rows, err := q.db.Query(ctx, selectNudgeEligiblePairs, arg.AfterDays, arg.RepeatDays, arg.MaxPairs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectNudgeEligiblePairsRow{}
	for rows.Next() {
		var i SelectNudgeEligiblePairsRow
		if err := rows.Scan(&i.UserID, &i.GroupID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBalanceNudge = `-- name: UpsertBalanceNudge :exec
INSERT INTO balance_nudges (user_id, group_id, last_nudged_at)
VALUES ($1, $2, NOW())
ON CONFLICT (user_id, group_id) DO UPDATE SET last_nudged_at = NOW()
`

type UpsertBalanceNudgeParams struct {
	UserID  string `db:"user_id" json:"user_id"`
	GroupID string `db:"group_id" json:"group_id"`
}

func (q *Queries) UpsertBalanceNudge(ctx context.Context, arg UpsertBalanceNudgeParams) error {
	_, err := q.db.Exec(ctx, upsertBalanceNudge, arg.UserID, arg.GroupID)
	return err
}
