// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: public_stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const publicExpenseStatsByCurrency = `-- name: PublicExpenseStatsByCurrency :many
SELECT
    e.currency,
    COUNT(*)::bigint       AS expense_count,
    SUM(e.amount)::bigint  AS total_minor
FROM expenses e
JOIN groups g ON g.id = e.group_id
WHERE NOT e.is_deleted
  AND NOT g.exclude_from_stats
GROUP BY e.currency
`

type PublicExpenseStatsByCurrencyRow struct {
	Currency     string `db:"currency" json:"currency"`
	ExpenseCount int64  `db:"expense_count" json:"expense_count"`
	TotalMinor   int64  `db:"total_minor" json:"total_minor"`
}

// Aggregates behind GET /api/public/stats. Deliberately returns nothing that
// identifies a group, a user or an individual expense — only per-currency
// counts and sums over non-deleted expenses in groups not flagged as demo
// data. Archived groups ARE included: an archived trip still happened, and
// excluding them would make the public counter go down over time.
func (q *Queries) PublicExpenseStatsByCurrency(ctx context.Context) ([]PublicExpenseStatsByCurrencyRow, error) {
	rows, err := q.db.Query(ctx, publicExpenseStatsByCurrency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicExpenseStatsByCurrencyRow{}
	for rows.Next() {
		var i PublicExpenseStatsByCurrencyRow
		if err := rows.Scan(&i.Currency, &i.ExpenseCount, &i.TotalMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publicStatsFirstExpenseDate = `-- name: PublicStatsFirstExpenseDate :one
SELECT MIN(e.created_at)::timestamptz AS first_created_at
FROM expenses e
JOIN groups g ON g.id = e.group_id
WHERE NOT e.is_deleted
  AND NOT g.exclude_from_stats
`

// Oldest counted expense, so the site can say "since <month year>" without
// hardcoding a launch date. NULL on an empty instance.
func (q *Queries) PublicStatsFirstExpenseDate(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, publicStatsFirstExpenseDate)
	var first_created_at pgtype.Timestamptz
	err := row.Scan(&first_created_at)
	return first_created_at, err
}
