// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: push_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePushToken = `-- name: DeletePushToken :exec
DELETE FROM push_tokens WHERE token = $1 AND user_id = $2
`

type DeletePushTokenParams struct {
	Token  string `db:"token" json:"token"`
	UserID string `db:"user_id" json:"user_id"`
}

func (q *Queries) DeletePushToken(ctx context.Context, arg DeletePushTokenParams) error {
	_, err := q.db.Exec(ctx, deletePushToken, arg.Token, arg.UserID)
	return err
}

const listPushTokensByGroup = `-- name: ListPushTokensByGroup :many
SELECT pt.id, pt.user_id, pt.token, pt.platform, pt.created_at, pt.last_used_at FROM push_tokens pt
JOIN group_members gm ON gm.user_id = pt.user_id
WHERE gm.group_id = $1 AND gm.user_id != $2
`

type ListPushTokensByGroupParams struct {
	GroupID string      `db:"group_id" json:"group_id"`
	UserID  pgtype.Text `db:"user_id" json:"user_id"`
}

func (q *Queries) ListPushTokensByGroup(ctx context.Context, arg ListPushTokensByGroupParams) ([]PushToken, error) {
	rows, err := q.db.Query(ctx, listPushTokensByGroup, arg.GroupID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushToken{}
	for rows.Next() {
		var i PushToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPushTokensByUser = `-- name: ListPushTokensByUser :many
SELECT id, user_id, token, platform, created_at, last_used_at FROM push_tokens WHERE user_id = $1
`

func (q *Queries) ListPushTokensByUser(ctx context.Context, userID string) ([]PushToken, error) {
	rows, err := q.db.Query(ctx, listPushTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushToken{}
	for rows.Next() {
		var i PushToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Platform,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPushToken = `-- name: UpsertPushToken :one
INSERT INTO push_tokens (id, user_id, token, platform)
VALUES ($1, $2, $3, $4)
ON CONFLICT (token) DO UPDATE
    SET user_id      = EXCLUDED.user_id,
        last_used_at = NOW()
RETURNING id, user_id, token, platform, created_at, last_used_at
`

type UpsertPushTokenParams struct {
	ID       string `db:"id" json:"id"`
	UserID   string `db:"user_id" json:"user_id"`
	Token    string `db:"token" json:"token"`
	Platform string `db:"platform" json:"platform"`
}

func (q *Queries) UpsertPushToken(ctx context.Context, arg UpsertPushTokenParams) (PushToken, error) {
	row := q.db.QueryRow(ctx, upsertPushToken,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.Platform,
	)
	var i PushToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Platform,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}
