// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: recurring.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceRecurringAfterFire = `-- name: AdvanceRecurringAfterFire :exec
UPDATE recurring_expenses
SET last_fire_at = $2, next_fire_at = $3, status = $4, updated_at = NOW()
WHERE id = $1
`

type AdvanceRecurringAfterFireParams struct {
	ID         string             `db:"id" json:"id"`
	LastFireAt pgtype.Timestamptz `db:"last_fire_at" json:"last_fire_at"`
	NextFireAt pgtype.Timestamptz `db:"next_fire_at" json:"next_fire_at"`
	Status     string             `db:"status" json:"status"`
}

func (q *Queries) AdvanceRecurringAfterFire(ctx context.Context, arg AdvanceRecurringAfterFireParams) error {
	_, err := q.db.Exec(ctx, advanceRecurringAfterFire,
		arg.ID,
		arg.LastFireAt,
		arg.NextFireAt,
		arg.Status,
	)
	return err
}

const createRecurringExpense = `-- name: CreateRecurringExpense :one
INSERT INTO recurring_expenses (
    id, group_id, title, amount_minor, currency,
    paid_by_id, split_method, category, notes,
    freq_unit, freq_interval, start_date, end_date,
    timezone, fire_local_time,
    status, next_fire_at, created_by_id
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13,
    $14, $15,
    'active', $16, $17
)
RETURNING id, group_id, title, amount_minor, currency, paid_by_id, split_method, category, notes, freq_unit, freq_interval, start_date, end_date, timezone, fire_local_time, status, paused_reason, last_fire_at, next_fire_at, created_by_id, created_at, updated_at
`

type CreateRecurringExpenseParams struct {
	ID            string             `db:"id" json:"id"`
	GroupID       string             `db:"group_id" json:"group_id"`
	Title         string             `db:"title" json:"title"`
	AmountMinor   int64              `db:"amount_minor" json:"amount_minor"`
	Currency      string             `db:"currency" json:"currency"`
	PaidByID      string             `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod   string             `db:"split_method" json:"split_method"`
	Category      string             `db:"category" json:"category"`
	Notes         pgtype.Text        `db:"notes" json:"notes"`
	FreqUnit      string             `db:"freq_unit" json:"freq_unit"`
	FreqInterval  int32              `db:"freq_interval" json:"freq_interval"`
	StartDate     pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate       pgtype.Date        `db:"end_date" json:"end_date"`
	Timezone      string             `db:"timezone" json:"timezone"`
	FireLocalTime pgtype.Time        `db:"fire_local_time" json:"fire_local_time"`
	NextFireAt    pgtype.Timestamptz `db:"next_fire_at" json:"next_fire_at"`
	CreatedByID   string             `db:"created_by_id" json:"created_by_id"`
}

func (q *Queries) CreateRecurringExpense(ctx context.Context, arg CreateRecurringExpenseParams) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, createRecurringExpense,
		arg.ID,
		arg.GroupID,
		arg.Title,
		arg.AmountMinor,
		arg.Currency,
		arg.PaidByID,
		arg.SplitMethod,
		arg.Category,
		arg.Notes,
		arg.FreqUnit,
		arg.FreqInterval,
		arg.StartDate,
		arg.EndDate,
		arg.Timezone,
		arg.FireLocalTime,
		arg.NextFireAt,
		arg.CreatedByID,
	)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.AmountMinor,
		&i.Currency,
		&i.PaidByID,
		&i.SplitMethod,
		&i.Category,
		&i.Notes,
		&i.FreqUnit,
		&i.FreqInterval,
		&i.StartDate,
		&i.EndDate,
		&i.Timezone,
		&i.FireLocalTime,
		&i.Status,
		&i.PausedReason,
		&i.LastFireAt,
		&i.NextFireAt,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRecurringSplit = `-- name: CreateRecurringSplit :exec
INSERT INTO recurring_expense_splits (recurring_id, member_id, value)
VALUES ($1, $2, $3)
`

type CreateRecurringSplitParams struct {
	RecurringID string `db:"recurring_id" json:"recurring_id"`
	MemberID    string `db:"member_id" json:"member_id"`
	Value       int64  `db:"value" json:"value"`
}

func (q *Queries) CreateRecurringSplit(ctx context.Context, arg CreateRecurringSplitParams) error {
	_, err := q.db.Exec(ctx, createRecurringSplit, arg.RecurringID, arg.MemberID, arg.Value)
	return err
}

const deleteRecurringExpense = `-- name: DeleteRecurringExpense :exec
DELETE FROM recurring_expenses WHERE id = $1
`

func (q *Queries) DeleteRecurringExpense(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRecurringExpense, id)
	return err
}

const deleteRecurringSplits = `-- name: DeleteRecurringSplits :exec
DELETE FROM recurring_expense_splits WHERE recurring_id = $1
`

func (q *Queries) DeleteRecurringSplits(ctx context.Context, recurringID string) error {
	_, err := q.db.Exec(ctx, deleteRecurringSplits, recurringID)
	return err
}

const getRecurringExpense = `-- name: GetRecurringExpense :one
SELECT id, group_id, title, amount_minor, currency, paid_by_id, split_method, category, notes, freq_unit, freq_interval, start_date, end_date, timezone, fire_local_time, status, paused_reason, last_fire_at, next_fire_at, created_by_id, created_at, updated_at FROM recurring_expenses WHERE id = $1
`

func (q *Queries) GetRecurringExpense(ctx context.Context, id string) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, getRecurringExpense, id)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.AmountMinor,
		&i.Currency,
		&i.PaidByID,
		&i.SplitMethod,
		&i.Category,
		&i.Notes,
		&i.FreqUnit,
		&i.FreqInterval,
		&i.StartDate,
		&i.EndDate,
		&i.Timezone,
		&i.FireLocalTime,
		&i.Status,
		&i.PausedReason,
		&i.LastFireAt,
		&i.NextFireAt,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecurringExpensesByGroup = `-- name: ListRecurringExpensesByGroup :many
SELECT id, group_id, title, amount_minor, currency, paid_by_id, split_method, category, notes, freq_unit, freq_interval, start_date, end_date, timezone, fire_local_time, status, paused_reason, last_fire_at, next_fire_at, created_by_id, created_at, updated_at FROM recurring_expenses WHERE group_id = $1
ORDER BY CASE status WHEN 'active' THEN 0 WHEN 'paused' THEN 1 ELSE 2 END,
         created_at DESC
`

func (q *Queries) ListRecurringExpensesByGroup(ctx context.Context, groupID string) ([]RecurringExpense, error) {
	rows, err := q.db.Query(ctx, listRecurringExpensesByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringExpense{}
	for rows.Next() {
		var i RecurringExpense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Title,
			&i.AmountMinor,
			&i.Currency,
			&i.PaidByID,
			&i.SplitMethod,
			&i.Category,
			&i.Notes,
			&i.FreqUnit,
			&i.FreqInterval,
			&i.StartDate,
			&i.EndDate,
			&i.Timezone,
			&i.FireLocalTime,
			&i.Status,
			&i.PausedReason,
			&i.LastFireAt,
			&i.NextFireAt,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringSplits = `-- name: ListRecurringSplits :many
SELECT recurring_id, member_id, value FROM recurring_expense_splits WHERE recurring_id = $1
`

func (q *Queries) ListRecurringSplits(ctx context.Context, recurringID string) ([]RecurringExpenseSplit, error) {
	rows, err := q.db.Query(ctx, listRecurringSplits, recurringID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringExpenseSplit{}
	for rows.Next() {
		var i RecurringExpenseSplit
		if err := rows.Scan(&i.RecurringID, &i.MemberID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseActiveRecurringExpensesByGroup = `-- name: PauseActiveRecurringExpensesByGroup :exec
UPDATE recurring_expenses
SET status = 'paused', paused_reason = $2, updated_at = NOW()
WHERE group_id = $1 AND status = 'active'
`

type PauseActiveRecurringExpensesByGroupParams struct {
	GroupID      string      `db:"group_id" json:"group_id"`
	PausedReason pgtype.Text `db:"paused_reason" json:"paused_reason"`
}

func (q *Queries) PauseActiveRecurringExpensesByGroup(ctx context.Context, arg PauseActiveRecurringExpensesByGroupParams) error {
	_, err := q.db.Exec(ctx, pauseActiveRecurringExpensesByGroup, arg.GroupID, arg.PausedReason)
	return err
}

const pauseRecurringExpensesAffectedByMember = `-- name: PauseRecurringExpensesAffectedByMember :many
UPDATE recurring_expenses r
SET status = 'paused', paused_reason = 'member_left', updated_at = NOW()
WHERE r.group_id = $1
  AND r.status = 'active'
  AND (r.paid_by_id = $2
       OR EXISTS (SELECT 1 FROM recurring_expense_splits s
                  WHERE s.recurring_id = r.id AND s.member_id = $2))
RETURNING id, created_by_id
`

type PauseRecurringExpensesAffectedByMemberParams struct {
	GroupID  string `db:"group_id" json:"group_id"`
	PaidByID string `db:"paid_by_id" json:"paid_by_id"`
}

type PauseRecurringExpensesAffectedByMemberRow struct {
	ID          string `db:"id" json:"id"`
	CreatedByID string `db:"created_by_id" json:"created_by_id"`
}

func (q *Queries) PauseRecurringExpensesAffectedByMember(ctx context.Context, arg PauseRecurringExpensesAffectedByMemberParams) ([]PauseRecurringExpensesAffectedByMemberRow, error) {
	rows, err := q.db.Query(ctx, pauseRecurringExpensesAffectedByMember, arg.GroupID, arg.PaidByID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PauseRecurringExpensesAffectedByMemberRow{}
	for rows.Next() {
		var i PauseRecurringExpensesAffectedByMemberRow
		if err := rows.Scan(&i.ID, &i.CreatedByID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resumeAllGroupLockedRecurringByCreator = `-- name: ResumeAllGroupLockedRecurringByCreator :many
UPDATE recurring_expenses
SET status = 'active', paused_reason = NULL,
    next_fire_at = NOW(), updated_at = NOW()
WHERE group_id = $1
  AND created_by_id = $2
  AND status = 'paused'
  AND paused_reason = 'group_locked'
RETURNING id
`

type ResumeAllGroupLockedRecurringByCreatorParams struct {
	GroupID     string `db:"group_id" json:"group_id"`
	CreatedByID string `db:"created_by_id" json:"created_by_id"`
}

func (q *Queries) ResumeAllGroupLockedRecurringByCreator(ctx context.Context, arg ResumeAllGroupLockedRecurringByCreatorParams) ([]string, error) {
	rows, err := q.db.Query(ctx, resumeAllGroupLockedRecurringByCreator, arg.GroupID, arg.CreatedByID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectDueRecurringExpenses = `-- name: SelectDueRecurringExpenses :many
SELECT id, next_fire_at FROM recurring_expenses
WHERE status = 'active' AND next_fire_at <= NOW()
ORDER BY next_fire_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type SelectDueRecurringExpensesRow struct {
	ID         string             `db:"id" json:"id"`
	NextFireAt pgtype.Timestamptz `db:"next_fire_at" json:"next_fire_at"`
}

func (q *Queries) SelectDueRecurringExpenses(ctx context.Context, limit int32) ([]SelectDueRecurringExpensesRow, error) {
	rows, err := q.db.Query(ctx, selectDueRecurringExpenses, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SelectDueRecurringExpensesRow{}
	for rows.Next() {
		var i SelectDueRecurringExpensesRow
		if err := rows.Scan(&i.ID, &i.NextFireAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRecurringStatus = `-- name: SetRecurringStatus :one
UPDATE recurring_expenses
SET status = $2, paused_reason = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, group_id, title, amount_minor, currency, paid_by_id, split_method, category, notes, freq_unit, freq_interval, start_date, end_date, timezone, fire_local_time, status, paused_reason, last_fire_at, next_fire_at, created_by_id, created_at, updated_at
`

type SetRecurringStatusParams struct {
	ID           string      `db:"id" json:"id"`
	Status       string      `db:"status" json:"status"`
	PausedReason pgtype.Text `db:"paused_reason" json:"paused_reason"`
}

func (q *Queries) SetRecurringStatus(ctx context.Context, arg SetRecurringStatusParams) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, setRecurringStatus, arg.ID, arg.Status, arg.PausedReason)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.AmountMinor,
		&i.Currency,
		&i.PaidByID,
		&i.SplitMethod,
		&i.Category,
		&i.Notes,
		&i.FreqUnit,
		&i.FreqInterval,
		&i.StartDate,
		&i.EndDate,
		&i.Timezone,
		&i.FireLocalTime,
		&i.Status,
		&i.PausedReason,
		&i.LastFireAt,
		&i.NextFireAt,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRecurringExpense = `-- name: UpdateRecurringExpense :one
UPDATE recurring_expenses SET
    title = $2, amount_minor = $3, paid_by_id = $4,
    split_method = $5, category = $6, notes = $7,
    freq_unit = $8, freq_interval = $9, end_date = $10,
    timezone = $11, fire_local_time = $12,
    next_fire_at = $13, updated_at = NOW()
WHERE id = $1
RETURNING id, group_id, title, amount_minor, currency, paid_by_id, split_method, category, notes, freq_unit, freq_interval, start_date, end_date, timezone, fire_local_time, status, paused_reason, last_fire_at, next_fire_at, created_by_id, created_at, updated_at
`

type UpdateRecurringExpenseParams struct {
	ID            string             `db:"id" json:"id"`
	Title         string             `db:"title" json:"title"`
	AmountMinor   int64              `db:"amount_minor" json:"amount_minor"`
	PaidByID      string             `db:"paid_by_id" json:"paid_by_id"`
	SplitMethod   string             `db:"split_method" json:"split_method"`
	Category      string             `db:"category" json:"category"`
	Notes         pgtype.Text        `db:"notes" json:"notes"`
	FreqUnit      string             `db:"freq_unit" json:"freq_unit"`
	FreqInterval  int32              `db:"freq_interval" json:"freq_interval"`
	EndDate       pgtype.Date        `db:"end_date" json:"end_date"`
	Timezone      string             `db:"timezone" json:"timezone"`
	FireLocalTime pgtype.Time        `db:"fire_local_time" json:"fire_local_time"`
	NextFireAt    pgtype.Timestamptz `db:"next_fire_at" json:"next_fire_at"`
}

func (q *Queries) UpdateRecurringExpense(ctx context.Context, arg UpdateRecurringExpenseParams) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, updateRecurringExpense,
		arg.ID,
		arg.Title,
		arg.AmountMinor,
		arg.PaidByID,
		arg.SplitMethod,
		arg.Category,
		arg.Notes,
		arg.FreqUnit,
		arg.FreqInterval,
		arg.EndDate,
		arg.Timezone,
		arg.FireLocalTime,
		arg.NextFireAt,
	)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.AmountMinor,
		&i.Currency,
		&i.PaidByID,
		&i.SplitMethod,
		&i.Category,
		&i.Notes,
		&i.FreqUnit,
		&i.FreqInterval,
		&i.StartDate,
		&i.EndDate,
		&i.Timezone,
		&i.FireLocalTime,
		&i.Status,
		&i.PausedReason,
		&i.LastFireAt,
		&i.NextFireAt,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
