// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: settle_reminders.sql

package db

import (
	"context"
)

const getSettleReminder = `-- name: GetSettleReminder :one
SELECT group_id, from_user_id, last_reminded_at
FROM settle_reminders
WHERE group_id = $1 AND from_user_id = $2
`

type GetSettleReminderParams struct {
	GroupID    string `db:"group_id" json:"group_id"`
	FromUserID string `db:"from_user_id" json:"from_user_id"`
}

func (q *Queries) GetSettleReminder(ctx context.Context, arg GetSettleReminderParams) (SettleReminder, error) {
	row := q.db.QueryRow(ctx, getSettleReminder, arg.GroupID, arg.FromUserID)
	var i SettleReminder
	err := row.Scan(&i.GroupID, &i.FromUserID, &i.LastRemindedAt)
	return i, err
}

const tryRecordSettleReminder = `-- name: TryRecordSettleReminder :one
INSERT INTO settle_reminders (group_id, from_user_id, last_reminded_at)
VALUES ($1, $2, NOW())
ON CONFLICT (group_id, from_user_id) DO UPDATE
    SET last_reminded_at = NOW()
    WHERE settle_reminders.last_reminded_at < NOW() - INTERVAL '48 hours'
RETURNING group_id, from_user_id, last_reminded_at
`

type TryRecordSettleReminderParams struct {
	GroupID    string `db:"group_id" json:"group_id"`
	FromUserID string `db:"from_user_id" json:"from_user_id"`
}

// Stamps a settle-up reminder for (group, creditor user), but only when the
// previous one is older than the 48h cooldown. Returns the row on success;
// returns no rows when still within the window (the handler reads that as
// "throttled"). First-ever reminder always inserts.
func (q *Queries) TryRecordSettleReminder(ctx context.Context, arg TryRecordSettleReminderParams) (SettleReminder, error) {
	row := q.db.QueryRow(ctx, tryRecordSettleReminder, arg.GroupID, arg.FromUserID)
	var i SettleReminder
	err := row.Scan(&i.GroupID, &i.FromUserID, &i.LastRemindedAt)
	return i, err
}
