// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: settlements.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSettlement = `-- name: CreateSettlement :one
INSERT INTO settlements (id, group_id, from_member, to_member, amount, currency, note, method, created_by_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, group_id, from_member, to_member, amount, currency, note, created_by_id, created_at, method, external_ref, reverted_at
`

type CreateSettlementParams struct {
	ID          string      `db:"id" json:"id"`
	GroupID     string      `db:"group_id" json:"group_id"`
	FromMember  string      `db:"from_member" json:"from_member"`
	ToMember    string      `db:"to_member" json:"to_member"`
	Amount      int64       `db:"amount" json:"amount"`
	Currency    string      `db:"currency" json:"currency"`
	Note        pgtype.Text `db:"note" json:"note"`
	Method      string      `db:"method" json:"method"`
	CreatedByID string      `db:"created_by_id" json:"created_by_id"`
}

func (q *Queries) CreateSettlement(ctx context.Context, arg CreateSettlementParams) (Settlement, error) {
	row := q.db.QueryRow(ctx, createSettlement,
		arg.ID,
		arg.GroupID,
		arg.FromMember,
		arg.ToMember,
		arg.Amount,
		arg.Currency,
		arg.Note,
		arg.Method,
		arg.CreatedByID,
	)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FromMember,
		&i.ToMember,
		&i.Amount,
		&i.Currency,
		&i.Note,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.Method,
		&i.ExternalRef,
		&i.RevertedAt,
	)
	return i, err
}

const getSettlement = `-- name: GetSettlement :one
SELECT id, group_id, from_member, to_member, amount, currency, note, created_by_id, created_at, method, external_ref, reverted_at FROM settlements WHERE id = $1
`

func (q *Queries) GetSettlement(ctx context.Context, id string) (Settlement, error) {
	row := q.db.QueryRow(ctx, getSettlement, id)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FromMember,
		&i.ToMember,
		&i.Amount,
		&i.Currency,
		&i.Note,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.Method,
		&i.ExternalRef,
		&i.RevertedAt,
	)
	return i, err
}

const listSettlementsByGroup = `-- name: ListSettlementsByGroup :many
SELECT id, group_id, from_member, to_member, amount, currency, note, created_by_id, created_at, method, external_ref, reverted_at FROM settlements
WHERE group_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSettlementsByGroup(ctx context.Context, groupID string) ([]Settlement, error) {
	rows, err := q.db.Query(ctx, listSettlementsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Settlement{}
	for rows.Next() {
		var i Settlement
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.FromMember,
			&i.ToMember,
			&i.Amount,
			&i.Currency,
			&i.Note,
			&i.CreatedByID,
			&i.CreatedAt,
			&i.Method,
			&i.ExternalRef,
			&i.RevertedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSettlementReverted = `-- name: MarkSettlementReverted :one
UPDATE settlements
SET reverted_at = NOW()
WHERE id = $1
  AND created_at > NOW() - INTERVAL '24 hours'
  AND reverted_at IS NULL
RETURNING id, group_id, from_member, to_member, amount, currency, note, created_by_id, created_at, method, external_ref, reverted_at
`

// Soft-revert a settlement. The caller (handler) is expected to have already
// enforced authorization (caller must be from_member or to_member's user)
// before calling this query. The query itself enforces the time gate
// (< 24h since creation) and the "not already reverted" guard, so a race
// between two reverts loses cleanly with pgx.ErrNoRows.
func (q *Queries) MarkSettlementReverted(ctx context.Context, id string) (Settlement, error) {
	row := q.db.QueryRow(ctx, markSettlementReverted, id)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FromMember,
		&i.ToMember,
		&i.Amount,
		&i.Currency,
		&i.Note,
		&i.CreatedByID,
		&i.CreatedAt,
		&i.Method,
		&i.ExternalRef,
		&i.RevertedAt,
	)
	return i, err
}
