// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: settlements.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSettlement = `-- name: CreateSettlement :one
INSERT INTO settlements (id, group_id, from_member, to_member, amount, currency, note, created_by_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, group_id, from_member, to_member, amount, currency, note, created_by_id, created_at
`

type CreateSettlementParams struct {
	ID          string      `db:"id" json:"id"`
	GroupID     string      `db:"group_id" json:"group_id"`
	FromMember  string      `db:"from_member" json:"from_member"`
	ToMember    string      `db:"to_member" json:"to_member"`
	Amount      int64       `db:"amount" json:"amount"`
	Currency    string      `db:"currency" json:"currency"`
	Note        pgtype.Text `db:"note" json:"note"`
	CreatedByID string      `db:"created_by_id" json:"created_by_id"`
}

func (q *Queries) CreateSettlement(ctx context.Context, arg CreateSettlementParams) (Settlement, error) {
	row := q.db.QueryRow(ctx, createSettlement,
		arg.ID,
		arg.GroupID,
		arg.FromMember,
		arg.ToMember,
		arg.Amount,
		arg.Currency,
		arg.Note,
		arg.CreatedByID,
	)
	var i Settlement
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.FromMember,
		&i.ToMember,
		&i.Amount,
		&i.Currency,
		&i.Note,
		&i.CreatedByID,
		&i.CreatedAt,
	)
	return i, err
}

const listSettlementsByGroup = `-- name: ListSettlementsByGroup :many
SELECT id, group_id, from_member, to_member, amount, currency, note, created_by_id, created_at FROM settlements
WHERE group_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSettlementsByGroup(ctx context.Context, groupID string) ([]Settlement, error) {
	rows, err := q.db.Query(ctx, listSettlementsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Settlement{}
	for rows.Next() {
		var i Settlement
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.FromMember,
			&i.ToMember,
			&i.Amount,
			&i.Currency,
			&i.Note,
			&i.CreatedByID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
