// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: summary.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const firstExpenseMonthForUser = `-- name: FirstExpenseMonthForUser :one
SELECT MIN(e.expense_date)::date AS first_expense_date
FROM expenses e
JOIN group_members gm ON gm.group_id = e.group_id AND gm.user_id = $1
LEFT JOIN expense_splits es ON es.expense_id = e.id AND es.member_id = gm.id
WHERE NOT e.is_deleted AND NOT e.is_reimbursement
  AND (e.paid_by_id = gm.id OR es.id IS NOT NULL)
`

// Oldest qualifying expense date for the user, so the screen can stop its
// "previous month" navigation instead of paging into empty months forever.
// NULL for a user who has never had a qualifying expense.
func (q *Queries) FirstExpenseMonthForUser(ctx context.Context, userID pgtype.Text) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, firstExpenseMonthForUser, userID)
	var first_expense_date pgtype.Date
	err := row.Scan(&first_expense_date)
	return first_expense_date, err
}

const listMonthlySummaryRecipients = `-- name: ListMonthlySummaryRecipients :many
SELECT u.id, u.locale
FROM users u
WHERE u.deleted_at IS NULL
  AND NOT u.monthly_summary_opt_out
  AND EXISTS (SELECT 1 FROM push_tokens pt WHERE pt.user_id = u.id)
  AND NOT EXISTS (
        SELECT 1 FROM monthly_summary_sends s
        WHERE s.user_id = u.id AND s.period = $1
      )
  AND EXISTS (
        SELECT 1
        FROM expenses e
        JOIN group_members gm ON gm.group_id = e.group_id AND gm.user_id = u.id
        LEFT JOIN expense_splits es ON es.expense_id = e.id AND es.member_id = gm.id
        WHERE NOT e.is_deleted AND NOT e.is_reimbursement
          AND e.expense_date >= $2 AND e.expense_date < $3
          AND (e.paid_by_id = gm.id OR es.id IS NOT NULL)
      )
ORDER BY u.id
LIMIT $5 OFFSET $4
`

type ListMonthlySummaryRecipientsParams struct {
	Period      string      `db:"period" json:"period"`
	PeriodStart pgtype.Date `db:"period_start" json:"period_start"`
	PeriodEnd   pgtype.Date `db:"period_end" json:"period_end"`
	Off         int32       `db:"off" json:"off"`
	Lim         int32       `db:"lim" json:"lim"`
}

type ListMonthlySummaryRecipientsRow struct {
	ID     string `db:"id" json:"id"`
	Locale string `db:"locale" json:"locale"`
}

// Users the monthly push should go to: has a device, not deleted, not opted
// out, not already notified for this period, and actually had spend. The
// ledger check is what makes the fan-out job resumable, so callers page by
// re-running with a fixed offset rather than advancing one.
func (q *Queries) ListMonthlySummaryRecipients(ctx context.Context, arg ListMonthlySummaryRecipientsParams) ([]ListMonthlySummaryRecipientsRow, error) {
	rows, err := q.db.Query(ctx, listMonthlySummaryRecipients,
		arg.Period,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMonthlySummaryRecipientsRow{}
	for rows.Next() {
		var i ListMonthlySummaryRecipientsRow
		if err := rows.Scan(&i.ID, &i.Locale); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMonthlySummarySent = `-- name: MarkMonthlySummarySent :exec
INSERT INTO monthly_summary_sends (user_id, period)
VALUES ($1, $2)
ON CONFLICT (user_id, period) DO NOTHING
`

type MarkMonthlySummarySentParams struct {
	UserID string `db:"user_id" json:"user_id"`
	Period string `db:"period" json:"period"`
}

// Records that the push for (user, period) has been attempted. ON CONFLICT
// DO NOTHING so a River retry that races another worker is a no-op rather
// than a unique violation that fails the whole job.
func (q *Queries) MarkMonthlySummarySent(ctx context.Context, arg MarkMonthlySummarySentParams) error {
	_, err := q.db.Exec(ctx, markMonthlySummarySent, arg.UserID, arg.Period)
	return err
}

const summaryActiveDays = `-- name: SummaryActiveDays :many
WITH mine AS (
    SELECT e.id, e.expense_date
    FROM expenses e
    JOIN group_members gm ON gm.group_id = e.group_id AND gm.user_id = $1
    LEFT JOIN expense_splits es ON es.expense_id = e.id AND es.member_id = gm.id
    WHERE NOT e.is_deleted AND NOT e.is_reimbursement
      AND e.expense_date >= $2 AND e.expense_date < $3
      AND (e.paid_by_id = gm.id OR es.id IS NOT NULL)
)
SELECT DISTINCT expense_date FROM mine ORDER BY expense_date
`

type SummaryActiveDaysParams struct {
	UserID      pgtype.Text `db:"user_id" json:"user_id"`
	PeriodStart pgtype.Date `db:"period_start" json:"period_start"`
	PeriodEnd   pgtype.Date `db:"period_end" json:"period_end"`
}

// The distinct dates the user had qualifying spend on, for the day grid in
// the summary screen. counts.active_days gives the tally; the grid needs to
// know WHICH days, and there is no way to derive that from a count.
func (q *Queries) SummaryActiveDays(ctx context.Context, arg SummaryActiveDaysParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, summaryActiveDays, arg.UserID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var expense_date pgtype.Date
		if err := rows.Scan(&expense_date); err != nil {
			return nil, err
		}
		items = append(items, expense_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryCounts = `-- name: SummaryCounts :one
WITH mine AS (
    SELECT e.id, e.group_id, e.expense_date
    FROM expenses e
    JOIN group_members gm ON gm.group_id = e.group_id AND gm.user_id = $1
    LEFT JOIN expense_splits es ON es.expense_id = e.id AND es.member_id = gm.id
    WHERE NOT e.is_deleted AND NOT e.is_reimbursement
      AND e.expense_date >= $2 AND e.expense_date < $3
      AND (e.paid_by_id = gm.id OR es.id IS NOT NULL)
)
SELECT COUNT(*)::bigint                     AS expense_count,
       COUNT(DISTINCT group_id)::bigint     AS group_count,
       COUNT(DISTINCT expense_date)::bigint AS active_days
FROM mine
`

type SummaryCountsParams struct {
	UserID      pgtype.Text `db:"user_id" json:"user_id"`
	PeriodStart pgtype.Date `db:"period_start" json:"period_start"`
	PeriodEnd   pgtype.Date `db:"period_end" json:"period_end"`
}

type SummaryCountsRow struct {
	ExpenseCount int64 `db:"expense_count" json:"expense_count"`
	GroupCount   int64 `db:"group_count" json:"group_count"`
	ActiveDays   int64 `db:"active_days" json:"active_days"`
}

// Currency-agnostic counts. Separate from the totals query because these
// must NOT be grouped by currency — a per-currency expense count would
// double-count a user whose month spans two.
func (q *Queries) SummaryCounts(ctx context.Context, arg SummaryCountsParams) (SummaryCountsRow, error) {
	row := q.db.QueryRow(ctx, summaryCounts, arg.UserID, arg.PeriodStart, arg.PeriodEnd)
	var i SummaryCountsRow
	err := row.Scan(&i.ExpenseCount, &i.GroupCount, &i.ActiveDays)
	return i, err
}

const summaryRowsForRanking = `-- name: SummaryRowsForRanking :many
WITH mine AS (
    SELECT e.id, e.group_id, e.currency, e.expense_date, e.category, e.title,
           COALESCE(es.share, 0) AS share
    FROM expenses e
    JOIN group_members gm ON gm.group_id = e.group_id AND gm.user_id = $1
    LEFT JOIN expense_splits es ON es.expense_id = e.id AND es.member_id = gm.id
    WHERE NOT e.is_deleted AND NOT e.is_reimbursement
      AND e.expense_date >= $2 AND e.expense_date < $3
      AND (e.paid_by_id = gm.id OR es.id IS NOT NULL)
)
SELECT m.id AS expense_id, m.group_id, g.name AS group_name,
       m.currency, m.expense_date, m.category, m.title,
       m.share::bigint AS share_minor
FROM mine m
JOIN groups g ON g.id = m.group_id
ORDER BY m.expense_date ASC, m.id ASC
`

type SummaryRowsForRankingParams struct {
	UserID      pgtype.Text `db:"user_id" json:"user_id"`
	PeriodStart pgtype.Date `db:"period_start" json:"period_start"`
	PeriodEnd   pgtype.Date `db:"period_end" json:"period_end"`
}

type SummaryRowsForRankingRow struct {
	ExpenseID   string      `db:"expense_id" json:"expense_id"`
	GroupID     string      `db:"group_id" json:"group_id"`
	GroupName   string      `db:"group_name" json:"group_name"`
	Currency    string      `db:"currency" json:"currency"`
	ExpenseDate pgtype.Date `db:"expense_date" json:"expense_date"`
	Category    string      `db:"category" json:"category"`
	Title       string      `db:"title" json:"title"`
	ShareMinor  int64       `db:"share_minor" json:"share_minor"`
}

// One row per qualifying expense. Deliberately NOT pre-aggregated: category
// totals, "biggest expense" and "top group" all rank across currencies, and
// that ranking is only meaningful after FX conversion, which happens in Go.
func (q *Queries) SummaryRowsForRanking(ctx context.Context, arg SummaryRowsForRankingParams) ([]SummaryRowsForRankingRow, error) {
	rows, err := q.db.Query(ctx, summaryRowsForRanking, arg.UserID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummaryRowsForRankingRow{}
	for rows.Next() {
		var i SummaryRowsForRankingRow
		if err := rows.Scan(
			&i.ExpenseID,
			&i.GroupID,
			&i.GroupName,
			&i.Currency,
			&i.ExpenseDate,
			&i.Category,
			&i.Title,
			&i.ShareMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summaryTotalsByCurrency = `-- name: SummaryTotalsByCurrency :many

WITH mine AS (
    SELECT e.id, e.currency,
           CASE WHEN e.paid_by_id = gm.id THEN e.amount ELSE 0 END AS paid,
           COALESCE(es.share, 0)                                   AS share
    FROM expenses e
    JOIN group_members gm ON gm.group_id = e.group_id AND gm.user_id = $1
    LEFT JOIN expense_splits es ON es.expense_id = e.id AND es.member_id = gm.id
    WHERE NOT e.is_deleted AND NOT e.is_reimbursement
      AND e.expense_date >= $2 AND e.expense_date < $3
      AND (e.paid_by_id = gm.id OR es.id IS NOT NULL)
)
SELECT currency,
       SUM(paid)::bigint  AS paid_minor,
       SUM(share)::bigint AS share_minor,
       COUNT(*)::bigint   AS expense_count
FROM mine
GROUP BY currency
ORDER BY currency ASC
`

type SummaryTotalsByCurrencyParams struct {
	UserID      pgtype.Text `db:"user_id" json:"user_id"`
	PeriodStart pgtype.Date `db:"period_start" json:"period_start"`
	PeriodEnd   pgtype.Date `db:"period_end" json:"period_end"`
}

type SummaryTotalsByCurrencyRow struct {
	Currency     string `db:"currency" json:"currency"`
	PaidMinor    int64  `db:"paid_minor" json:"paid_minor"`
	ShareMinor   int64  `db:"share_minor" json:"share_minor"`
	ExpenseCount int64  `db:"expense_count" json:"expense_count"`
}

// Queries behind the monthly summary (GET /api/me/summary) and the monthly
// push job. Every aggregate derives from the same `mine` CTE: the expenses
// one user either paid for or holds a split in, over one calendar month.
//
// The filter mirrors the member_balances view (NOT is_deleted AND NOT
// is_reimbursement) so "net" on the summary page reconciles with the
// balances shown everywhere else. Archived groups are included — an
// archived trip still happened — and group_members.removed_at is ignored,
// because spend in a group the user has since left was still their spend.
//
// sqlc cannot return several result sets from one statement, so the CTE is
// repeated per shape. Do not try to merge them.
//
// Spec: docs/superpowers/specs/2026-09-02-monthly-summary-design.md
// Per-currency paid/share. No FX: this is the unconverted source of truth
// the page always renders somewhere.
func (q *Queries) SummaryTotalsByCurrency(ctx context.Context, arg SummaryTotalsByCurrencyParams) ([]SummaryTotalsByCurrencyRow, error) {
	rows, err := q.db.Query(ctx, summaryTotalsByCurrency, arg.UserID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SummaryTotalsByCurrencyRow{}
	for rows.Next() {
		var i SummaryTotalsByCurrencyRow
		if err := rows.Scan(
			&i.Currency,
			&i.PaidMinor,
			&i.ShareMinor,
			&i.ExpenseCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
