// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: usage_counters.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUsageCounter = `-- name: GetUsageCounter :one

SELECT user_id, feature, period_start, used
FROM usage_counters
WHERE user_id = $1 AND feature = $2
`

type GetUsageCounterParams struct {
	UserID  string `db:"user_id" json:"user_id"`
	Feature string `db:"feature" json:"feature"`
}

// usage_counters: per-user, per-feature metered usage on the hosted instance.
// v1.0 use case: anti-abuse cap on free OCR (3/month). The hot path is the
// reserve-and-refund pair; GetUsageCounter exists for the You-tab display.
// Read current state (used for UI display). Stale period_start means a
// ReserveUsageSlot call would lazy-reset and return used=1; surfaces of this
// query MUST account for that themselves (see internal/billing/counter.go).
func (q *Queries) GetUsageCounter(ctx context.Context, arg GetUsageCounterParams) (UsageCounter, error) {
	row := q.db.QueryRow(ctx, getUsageCounter, arg.UserID, arg.Feature)
	var i UsageCounter
	err := row.Scan(
		&i.UserID,
		&i.Feature,
		&i.PeriodStart,
		&i.Used,
	)
	return i, err
}

const refundUsageSlot = `-- name: RefundUsageSlot :exec
UPDATE usage_counters
SET used = used - 1
WHERE user_id = $1
  AND feature = $2
  AND period_start = $3
  AND used > 0
`

type RefundUsageSlotParams struct {
	UserID      string      `db:"user_id" json:"user_id"`
	Feature     string      `db:"feature" json:"feature"`
	PeriodStart pgtype.Date `db:"period_start" json:"period_start"`
}

// Decrement after a downstream failure (e.g. Gemini rejected the image).
// Guarded by period_start = current so a refund attempt that crosses a
// month boundary doesn't decrement a freshly-reset counter. used > 0 makes
// the decrement crash-safe under retries.
func (q *Queries) RefundUsageSlot(ctx context.Context, arg RefundUsageSlotParams) error {
	_, err := q.db.Exec(ctx, refundUsageSlot, arg.UserID, arg.Feature, arg.PeriodStart)
	return err
}

const reserveUsageSlot = `-- name: ReserveUsageSlot :one
INSERT INTO usage_counters (user_id, feature, period_start, used)
VALUES ($1, $2, $3, 1)
ON CONFLICT (user_id, feature) DO UPDATE
SET
    period_start = CASE
        WHEN usage_counters.period_start < EXCLUDED.period_start
            THEN EXCLUDED.period_start
        ELSE usage_counters.period_start
    END,
    used = CASE
        WHEN usage_counters.period_start < EXCLUDED.period_start THEN 1
        ELSE usage_counters.used + 1
    END
WHERE usage_counters.period_start < EXCLUDED.period_start
   OR usage_counters.used < $4::int
RETURNING user_id, feature, period_start, used
`

type ReserveUsageSlotParams struct {
	UserID      string      `db:"user_id" json:"user_id"`
	Feature     string      `db:"feature" json:"feature"`
	PeriodStart pgtype.Date `db:"period_start" json:"period_start"`
	Cap         int32       `db:"cap" json:"cap"`
}

// Atomically reserve a slot under the given cap. Combines lazy-reset across a
// UTC month boundary with the increment, so the whole flow is one round-trip.
//
// Semantics:
//   - Fresh user (no row) → INSERT used=1, period_start=current. Returns row.
//   - Existing row in current period, used < cap → UPDATE used+1. Returns row.
//   - Existing row in current period, used >= cap → WHERE filters out the
//     UPDATE; no row is returned. Caller treats 0 rows as "cap reached".
//   - Existing row in a *prior* period → period_start advances, used=1.
//     Returns row.
//
// The WHERE on ON CONFLICT does the gating; PostgreSQL guarantees the
// INSERT/UPDATE is atomic, so concurrent callers can't both pass the cap.
// Parameters: user_id, feature, cap, period_start (current 1st-of-UTC-month
// date, accepted as a parameter so tests can inject month boundaries
// deterministically without freezing time).
func (q *Queries) ReserveUsageSlot(ctx context.Context, arg ReserveUsageSlotParams) (UsageCounter, error) {
	row := q.db.QueryRow(ctx, reserveUsageSlot,
		arg.UserID,
		arg.Feature,
		arg.PeriodStart,
		arg.Cap,
	)
	var i UsageCounter
	err := row.Scan(
		&i.UserID,
		&i.Feature,
		&i.PeriodStart,
		&i.Used,
	)
	return i, err
}
