// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_feature_caps.sql

package db

import (
	"context"
)

const getFeatureCap = `-- name: GetFeatureCap :one
SELECT cap FROM user_feature_caps
WHERE user_id = $1 AND feature = $2
`

type GetFeatureCapParams struct {
	UserID  string `db:"user_id" json:"user_id"`
	Feature string `db:"feature" json:"feature"`
}

// Per-user, per-feature cap override for hosted metering. No row = use the
// global default cap; >= 0 = explicit cap; < 0 = unlimited (bypassed).
func (q *Queries) GetFeatureCap(ctx context.Context, arg GetFeatureCapParams) (int32, error) {
	row := q.db.QueryRow(ctx, getFeatureCap, arg.UserID, arg.Feature)
	var cap int32
	err := row.Scan(&cap)
	return cap, err
}

const setFeatureCap = `-- name: SetFeatureCap :exec
INSERT INTO user_feature_caps (user_id, feature, cap)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, feature) DO UPDATE SET cap = EXCLUDED.cap
`

type SetFeatureCapParams struct {
	UserID  string `db:"user_id" json:"user_id"`
	Feature string `db:"feature" json:"feature"`
	Cap     int32  `db:"cap" json:"cap"`
}

func (q *Queries) SetFeatureCap(ctx context.Context, arg SetFeatureCapParams) error {
	_, err := q.db.Exec(ctx, setFeatureCap, arg.UserID, arg.Feature, arg.Cap)
	return err
}
