// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: waitlist_signups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWaitlistByTrigger = `-- name: CountWaitlistByTrigger :one
SELECT COUNT(*) AS total
FROM waitlist_signups
WHERE trigger = $1
`

// Debugging / dashboard query. Cheap because of the (trigger, created_at)
// index. Not used on a hot path.
func (q *Queries) CountWaitlistByTrigger(ctx context.Context, trigger string) (int64, error) {
	row := q.db.QueryRow(ctx, countWaitlistByTrigger, trigger)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const upsertWaitlistSignup = `-- name: UpsertWaitlistSignup :one

INSERT INTO waitlist_signups (id, user_id, email, trigger, source, locale)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, email, trigger) DO UPDATE
SET last_seen_at = NOW()
RETURNING id, user_id, email, trigger, source, locale, created_at, last_seen_at
`

type UpsertWaitlistSignupParams struct {
	ID      string      `db:"id" json:"id"`
	UserID  pgtype.Text `db:"user_id" json:"user_id"`
	Email   string      `db:"email" json:"email"`
	Trigger string      `db:"trigger" json:"trigger"`
	Source  pgtype.Text `db:"source" json:"source"`
	Locale  pgtype.Text `db:"locale" json:"locale"`
}

// waitlist_signups: hosted-instance soft-gate email capture during the
// v1.0/v1.1 free beta. Primary trigger is the OCR cap modal; future triggers
// (recurring expense tap, export tap) reuse this table.
// Idempotent on (user_id, email, trigger) so re-tapping the same gate just
// bumps last_seen_at instead of duplicating rows. We deliberately don't
// merge across different triggers — distinct triggers are independent
// signals about which feature the user wants.
func (q *Queries) UpsertWaitlistSignup(ctx context.Context, arg UpsertWaitlistSignupParams) (WaitlistSignup, error) {
	row := q.db.QueryRow(ctx, upsertWaitlistSignup,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.Trigger,
		arg.Source,
		arg.Locale,
	)
	var i WaitlistSignup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Trigger,
		&i.Source,
		&i.Locale,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
