/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DeleteRouteImport } from './routes/delete'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SelfHostRouteImport } from './routes/self-host'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SplitwiseAlternativeRouteImport } from './routes/splitwise-alternative'
import { Route as SplitwiseDailyLimitRouteImport } from './routes/splitwise-daily-limit'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SwitchFromSplitwiseRouteImport } from './routes/switch-from-splitwise'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VsSlugRouteImport } from './routes/vs.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteRoute = DeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfHostRoute = SelfHostRouteImport.update({
  id: '/self-host',
  path: '/self-host',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitwiseAlternativeRoute = SplitwiseAlternativeRouteImport.update({
  id: '/splitwise-alternative',
  path: '/splitwise-alternative',
  getParentRoute: () => rootRouteImport,
} as any)
const SplitwiseDailyLimitRoute = SplitwiseDailyLimitRouteImport.update({
  id: '/splitwise-daily-limit',
  path: '/splitwise-daily-limit',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SwitchFromSplitwiseRoute = SwitchFromSplitwiseRouteImport.update({
  id: '/switch-from-splitwise',
  path: '/switch-from-splitwise',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VsSlugRoute = VsSlugRouteImport.update({
  id: '/vs/$slug',
  path: '/vs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/delete': typeof DeleteRoute
  '/dpa': typeof DpaRoute
  '/privacy': typeof PrivacyRoute
  '/releases': typeof ReleasesRoute
  '/security': typeof SecurityRoute
  '/self-host': typeof SelfHostRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/splitwise-alternative': typeof SplitwiseAlternativeRoute
  '/splitwise-daily-limit': typeof SplitwiseDailyLimitRoute
  '/support': typeof SupportRoute
  '/switch-from-splitwise': typeof SwitchFromSplitwiseRoute
  '/terms': typeof TermsRoute
  '/vs/$slug': typeof VsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/delete': typeof DeleteRoute
  '/dpa': typeof DpaRoute
  '/privacy': typeof PrivacyRoute
  '/releases': typeof ReleasesRoute
  '/security': typeof SecurityRoute
  '/self-host': typeof SelfHostRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/splitwise-alternative': typeof SplitwiseAlternativeRoute
  '/splitwise-daily-limit': typeof SplitwiseDailyLimitRoute
  '/support': typeof SupportRoute
  '/switch-from-splitwise': typeof SwitchFromSplitwiseRoute
  '/terms': typeof TermsRoute
  '/vs/$slug': typeof VsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/delete': typeof DeleteRoute
  '/dpa': typeof DpaRoute
  '/privacy': typeof PrivacyRoute
  '/releases': typeof ReleasesRoute
  '/security': typeof SecurityRoute
  '/self-host': typeof SelfHostRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/splitwise-alternative': typeof SplitwiseAlternativeRoute
  '/splitwise-daily-limit': typeof SplitwiseDailyLimitRoute
  '/support': typeof SupportRoute
  '/switch-from-splitwise': typeof SwitchFromSplitwiseRoute
  '/terms': typeof TermsRoute
  '/vs/$slug': typeof VsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/delete'
    | '/dpa'
    | '/privacy'
    | '/releases'
    | '/security'
    | '/self-host'
    | '/sitemap.xml'
    | '/splitwise-alternative'
    | '/splitwise-daily-limit'
    | '/support'
    | '/switch-from-splitwise'
    | '/terms'
    | '/vs/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/delete'
    | '/dpa'
    | '/privacy'
    | '/releases'
    | '/security'
    | '/self-host'
    | '/sitemap.xml'
    | '/splitwise-alternative'
    | '/splitwise-daily-limit'
    | '/support'
    | '/switch-from-splitwise'
    | '/terms'
    | '/vs/$slug'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/delete'
    | '/dpa'
    | '/privacy'
    | '/releases'
    | '/security'
    | '/self-host'
    | '/sitemap.xml'
    | '/splitwise-alternative'
    | '/splitwise-daily-limit'
    | '/support'
    | '/switch-from-splitwise'
    | '/terms'
    | '/vs/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  DeleteRoute: typeof DeleteRoute
  DpaRoute: typeof DpaRoute
  PrivacyRoute: typeof PrivacyRoute
  ReleasesRoute: typeof ReleasesRoute
  SecurityRoute: typeof SecurityRoute
  SelfHostRoute: typeof SelfHostRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SplitwiseAlternativeRoute: typeof SplitwiseAlternativeRoute
  SplitwiseDailyLimitRoute: typeof SplitwiseDailyLimitRoute
  SupportRoute: typeof SupportRoute
  SwitchFromSplitwiseRoute: typeof SwitchFromSplitwiseRoute
  TermsRoute: typeof TermsRoute
  VsSlugRoute: typeof VsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete': {
      id: '/delete'
      path: '/delete'
      fullPath: '/delete'
      preLoaderRoute: typeof DeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-host': {
      id: '/self-host'
      path: '/self-host'
      fullPath: '/self-host'
      preLoaderRoute: typeof SelfHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splitwise-alternative': {
      id: '/splitwise-alternative'
      path: '/splitwise-alternative'
      fullPath: '/splitwise-alternative'
      preLoaderRoute: typeof SplitwiseAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splitwise-daily-limit': {
      id: '/splitwise-daily-limit'
      path: '/splitwise-daily-limit'
      fullPath: '/splitwise-daily-limit'
      preLoaderRoute: typeof SplitwiseDailyLimitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/switch-from-splitwise': {
      id: '/switch-from-splitwise'
      path: '/switch-from-splitwise'
      fullPath: '/switch-from-splitwise'
      preLoaderRoute: typeof SwitchFromSplitwiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/$slug': {
      id: '/vs/$slug'
      path: '/vs/$slug'
      fullPath: '/vs/$slug'
      preLoaderRoute: typeof VsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  DeleteRoute: DeleteRoute,
  DpaRoute: DpaRoute,
  PrivacyRoute: PrivacyRoute,
  ReleasesRoute: ReleasesRoute,
  SecurityRoute: SecurityRoute,
  SelfHostRoute: SelfHostRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SplitwiseAlternativeRoute: SplitwiseAlternativeRoute,
  SplitwiseDailyLimitRoute: SplitwiseDailyLimitRoute,
  SupportRoute: SupportRoute,
  SwitchFromSplitwiseRoute: SwitchFromSplitwiseRoute,
  TermsRoute: TermsRoute,
  VsSlugRoute: VsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
